# Generated by Django 6.0.3 on 2026-03-24 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(db_index=True, help_text='UID do Firebase Authentication', max_length=128, unique=True)),
                ('auth_provider', models.CharField(default='password', help_text='Provider usado no login (google.com, password, oidc.orcid)', max_length=50)),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID iD do pesquisador (formato: 0000-0000-0000-0000)', max_length=50, null=True, unique=True)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('research_area', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('last_firebase_sync', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'accounts_userprofile',
            },
        ),
    ]
