# Generated by Django 6.0.3 on 2026-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ncbi_api_key',
            field=models.CharField(blank=True, default='', help_text='NCBI API Key pessoal (eleva rate limit de 3 para 10 req/s)', max_length=255),
        ),
    ]
