/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfil do usuário autenticado
         * @description Retorna (criando se necessário) o UserProfile do usuário Firebase autenticado.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar perfil do usuário
         * @description Atualiza campos de perfil (institution, research_area, orcid_id, first_name, last_name).
         */
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verificar token Firebase
         * @description Retorna 200 com status=valid se o token Bearer é válido. 401 caso contrário.
         */
        post: operations["auth_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinical-categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only global clinical categories.
         *     GET /api/v1/clinical-categories/
         */
        get: operations["clinical_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_list"];
        put?: never;
        post: operations["projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_retrieve"];
        put: operations["projects_update"];
        post?: never;
        delete: operations["projects_destroy"];
        options?: never;
        head?: never;
        patch: operations["projects_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{id}/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar papers incluídos
         * @description Exporta papers com curation_status=included em JSON (padrão) ou CSV (?export_format=csv).
         */
        get: operations["projects_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/omics_search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disparar busca ômica
         * @description Cria e enfileira um job de busca em GEO/SRA/BioProject/GWAS para o projeto.
         */
        post: operations["projects_omics_search_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disparar busca PubMed
         * @description Cria e enfileira um job de busca de literatura no PubMed para o projeto.
         */
        post: operations["projects_search_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estatísticas do projeto
         * @description Retorna ProjectStats calculadas on-the-fly se ausentes.
         */
        get: operations["projects_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD for project-scoped custom categories.
         *     /projects/{project_pk}/categories/
         */
        get: operations["projects_categories_list"];
        put?: never;
        /**
         * @description CRUD for project-scoped custom categories.
         *     /projects/{project_pk}/categories/
         */
        post: operations["projects_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description CRUD for project-scoped custom categories.
         *     /projects/{project_pk}/categories/
         */
        delete: operations["projects_categories_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD for project-scoped custom categories.
         *     /projects/{project_pk}/categories/
         */
        patch: operations["projects_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de datasets ômicos dentro de um projeto.
         *
         *     list:   GET  /projects/{project_pk}/datasets/
         *     detail: GET  /projects/{project_pk}/datasets/{id}/
         *     patch:  PATCH /projects/{project_pk}/datasets/{id}/
         *     search: GET  /projects/{project_pk}/datasets/search/?q=term
         */
        get: operations["projects_datasets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/datasets/{dataset_pk}/samples/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de amostras ômicas dentro de um projeto.
         *
         *     Rotas registradas em urls.py:
         *       list/filter:  GET  /projects/{project_pk}/samples/
         *       detail:       GET  /projects/{project_pk}/samples/{id}/
         *       patch:        PATCH /projects/{project_pk}/samples/{id}/
         *       bulk_curate:  POST /projects/{project_pk}/samples/bulk_curate/
         *
         *     Rota por dataset (para a página de samples de um dataset específico):
         *       GET  /projects/{project_pk}/datasets/{dataset_pk}/samples/
         *       (mesma view, parâmetro dataset_pk opcional tratado em get_queryset)
         *
         *     firebase-auth-guard: _get_project filtra sempre por request.user.
         *     curation-audit-trail: perform_update e bulk_curate setam curated_at;
         *       sem DELETE — exclusão é curation_status='excluded'.
         *     postgres-fts-patterns: select_related em todos os querysets (sem N+1).
         */
        get: operations["projects_datasets_samples_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/datasets/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de datasets ômicos dentro de um projeto.
         *
         *     list:   GET  /projects/{project_pk}/datasets/
         *     detail: GET  /projects/{project_pk}/datasets/{id}/
         *     patch:  PATCH /projects/{project_pk}/datasets/{id}/
         *     search: GET  /projects/{project_pk}/datasets/search/?q=term
         */
        get: operations["projects_datasets_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Curadoria de datasets ômicos dentro de um projeto.
         *
         *     list:   GET  /projects/{project_pk}/datasets/
         *     detail: GET  /projects/{project_pk}/datasets/{id}/
         *     patch:  PATCH /projects/{project_pk}/datasets/{id}/
         *     search: GET  /projects/{project_pk}/datasets/search/?q=term
         */
        patch: operations["projects_datasets_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/datasets/bulk_curate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Curadoria em massa de datasets
         * @description Atualiza curation_status de múltiplos ProjectDatasets. Dispara SAMPLE_FETCH para os incluídos.
         */
        post: operations["projects_datasets_bulk_curate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/datasets/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca FTS em datasets do projeto
         * @description Busca full-text em datasets do projeto via search_vector. Parâmetro obrigatório: ?q=termo.
         */
        get: operations["projects_datasets_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read + cancel ingestion jobs for a project.
         *
         *     list:   GET  /projects/{project_pk}/jobs/
         *     detail: GET  /projects/{project_pk}/jobs/{id}/
         *     cancel: POST /projects/{project_pk}/jobs/{id}/cancel/
         */
        get: operations["projects_jobs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read + cancel ingestion jobs for a project.
         *
         *     list:   GET  /projects/{project_pk}/jobs/
         *     detail: GET  /projects/{project_pk}/jobs/{id}/
         *     cancel: POST /projects/{project_pk}/jobs/{id}/cancel/
         */
        get: operations["projects_jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/jobs/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar job de ingestão
         * @description Cancela um job que ainda não atingiu estado terminal (completed/failed).
         */
        post: operations["projects_jobs_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/links/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Literature ↔ Omics links within a project.
         *
         *     list:    GET  /projects/{project_pk}/links/
         *     confirm: POST /projects/{project_pk}/links/{id}/confirm/
         *     reject:  POST /projects/{project_pk}/links/{id}/reject/
         */
        get: operations["projects_links_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/links/{id}/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar link literatura-ômica
         * @description Define confidence=confirmed no link entre paper e dataset.
         */
        post: operations["projects_links_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/links/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejeitar link literatura-ômica
         * @description Define confidence=rejected no link entre paper e dataset.
         */
        post: operations["projects_links_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/papers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de papers dentro de um projeto.
         *
         *     list:   GET  /projects/{project_pk}/papers/
         *     detail: GET  /projects/{project_pk}/papers/{id}/
         *     patch:  PATCH /projects/{project_pk}/papers/{id}/
         *     categorize: POST /projects/{project_pk}/papers/{id}/categorize/
         *     bulk_curate: POST /projects/{project_pk}/papers/bulk_curate/
         *     search: GET  /projects/{project_pk}/papers/search/?q=term
         */
        get: operations["projects_papers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/papers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de papers dentro de um projeto.
         *
         *     list:   GET  /projects/{project_pk}/papers/
         *     detail: GET  /projects/{project_pk}/papers/{id}/
         *     patch:  PATCH /projects/{project_pk}/papers/{id}/
         *     categorize: POST /projects/{project_pk}/papers/{id}/categorize/
         *     bulk_curate: POST /projects/{project_pk}/papers/bulk_curate/
         *     search: GET  /projects/{project_pk}/papers/search/?q=term
         */
        get: operations["projects_papers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Curadoria de papers dentro de um projeto.
         *
         *     list:   GET  /projects/{project_pk}/papers/
         *     detail: GET  /projects/{project_pk}/papers/{id}/
         *     patch:  PATCH /projects/{project_pk}/papers/{id}/
         *     categorize: POST /projects/{project_pk}/papers/{id}/categorize/
         *     bulk_curate: POST /projects/{project_pk}/papers/bulk_curate/
         *     search: GET  /projects/{project_pk}/papers/search/?q=term
         */
        patch: operations["projects_papers_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/papers/{id}/categorize/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Categorizar paper
         * @description Adiciona ou remove categorias clínicas e de usuário de um ProjectPaper.
         */
        post: operations["projects_papers_categorize_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/papers/bulk_curate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Curadoria em massa de papers
         * @description Atualiza curation_status de múltiplos ProjectPapers em uma operação.
         */
        post: operations["projects_papers_bulk_curate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/papers/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca FTS em papers do projeto
         * @description Busca full-text em papers do projeto via search_vector. Parâmetro obrigatório: ?q=termo.
         */
        get: operations["projects_papers_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/samples/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de amostras ômicas dentro de um projeto.
         *
         *     Rotas registradas em urls.py:
         *       list/filter:  GET  /projects/{project_pk}/samples/
         *       detail:       GET  /projects/{project_pk}/samples/{id}/
         *       patch:        PATCH /projects/{project_pk}/samples/{id}/
         *       bulk_curate:  POST /projects/{project_pk}/samples/bulk_curate/
         *
         *     Rota por dataset (para a página de samples de um dataset específico):
         *       GET  /projects/{project_pk}/datasets/{dataset_pk}/samples/
         *       (mesma view, parâmetro dataset_pk opcional tratado em get_queryset)
         *
         *     firebase-auth-guard: _get_project filtra sempre por request.user.
         *     curation-audit-trail: perform_update e bulk_curate setam curated_at;
         *       sem DELETE — exclusão é curation_status='excluded'.
         *     postgres-fts-patterns: select_related em todos os querysets (sem N+1).
         */
        get: operations["projects_samples_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/samples/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curadoria de amostras ômicas dentro de um projeto.
         *
         *     Rotas registradas em urls.py:
         *       list/filter:  GET  /projects/{project_pk}/samples/
         *       detail:       GET  /projects/{project_pk}/samples/{id}/
         *       patch:        PATCH /projects/{project_pk}/samples/{id}/
         *       bulk_curate:  POST /projects/{project_pk}/samples/bulk_curate/
         *
         *     Rota por dataset (para a página de samples de um dataset específico):
         *       GET  /projects/{project_pk}/datasets/{dataset_pk}/samples/
         *       (mesma view, parâmetro dataset_pk opcional tratado em get_queryset)
         *
         *     firebase-auth-guard: _get_project filtra sempre por request.user.
         *     curation-audit-trail: perform_update e bulk_curate setam curated_at;
         *       sem DELETE — exclusão é curation_status='excluded'.
         *     postgres-fts-patterns: select_related em todos os querysets (sem N+1).
         */
        get: operations["projects_samples_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Curadoria de amostras ômicas dentro de um projeto.
         *
         *     Rotas registradas em urls.py:
         *       list/filter:  GET  /projects/{project_pk}/samples/
         *       detail:       GET  /projects/{project_pk}/samples/{id}/
         *       patch:        PATCH /projects/{project_pk}/samples/{id}/
         *       bulk_curate:  POST /projects/{project_pk}/samples/bulk_curate/
         *
         *     Rota por dataset (para a página de samples de um dataset específico):
         *       GET  /projects/{project_pk}/datasets/{dataset_pk}/samples/
         *       (mesma view, parâmetro dataset_pk opcional tratado em get_queryset)
         *
         *     firebase-auth-guard: _get_project filtra sempre por request.user.
         *     curation-audit-trail: perform_update e bulk_curate setam curated_at;
         *       sem DELETE — exclusão é curation_status='excluded'.
         *     postgres-fts-patterns: select_related em todos os querysets (sem N+1).
         */
        patch: operations["projects_samples_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{project_pk}/samples/bulk_curate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Curadoria em massa de samples
         * @description Atualiza curation_status de múltiplos ProjectSamples em uma operação.
         */
        post: operations["projects_samples_bulk_curate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        /** @description Resposta genérica de operações bulk: quantidade de registros atualizados. */
        BulkCurateResponse: {
            updated: number;
        };
        ClinicalCategory: {
            readonly id: number;
            slug: string;
            /** Nome */
            name: string;
            /** Descrição */
            description?: string;
            /**
             * Keywords de Classificação
             * @description Termos usados pelo Rust para detectar esta categoria no abstract
             */
            keywords?: unknown;
            /**
             * Categoria Padrão
             * @description True para os 5 eixos padrão (não deletável)
             */
            is_default?: boolean;
            /** Prioridade */
            priority?: number;
        };
        ClinicalCategoryBrief: {
            readonly id: number;
            slug: string;
            /** Nome */
            name: string;
        };
        /**
         * @description * `auto` - Automático (elink/co-ocorrência)
         *     * `confirmed` - Confirmado pelo Pesquisador
         *     * `rejected` - Rejeitado pelo Pesquisador
         * @enum {string}
         */
        ConfidenceEnum: "auto" | "confirmed" | "rejected";
        /**
         * @description * `pending` - Pendente
         *     * `included` - Incluído
         *     * `excluded` - Excluído
         *     * `maybe` - Talvez
         * @enum {string}
         */
        CurationStatusEnum: "pending" | "included" | "excluded" | "maybe";
        DaVinciProject: {
            /** Format: uuid */
            readonly id: string;
            query_synonyms?: string[];
            target_organisms?: string[];
            target_tissues?: string[];
            /** @default 0 */
            readonly total_papers: number;
            /** @default 0 */
            readonly total_datasets: number;
            /**
             * Identificador
             * @description Gerado automaticamente: {titulo}_{user}_davinci
             */
            readonly slug: string;
            /** Título do Projeto */
            title: string;
            /** Descrição */
            description?: string;
            /**
             * Termo de Busca Principal
             * @description Ex: "hidradenitis AND cancer", "cardiovascular disease"
             */
            query_term: string;
            /** Ano Inicial */
            date_from?: number | null;
            /** Ano Final */
            date_to?: number | null;
            readonly status: components["schemas"]["DaVinciProjectStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly user: number;
        };
        /**
         * @description * `draft` - Rascunho
         *     * `searching` - Buscando
         *     * `curating` - Em Curadoria
         *     * `analyzing` - Analisando
         *     * `complete` - Completo
         * @enum {string}
         */
        DaVinciProjectStatusEnum: "draft" | "searching" | "curating" | "analyzing" | "complete";
        /** @description Body de bulk_curate de datasets. */
        DatasetBulkCurateRequest: {
            /** @description Lista de IDs de ProjectDataset a atualizar. */
            dataset_ids: number[];
            /**
             * @description Status de curadoria a aplicar.
             *
             *     * `pending` - Pendente
             *     * `included` - Incluído
             *     * `excluded` - Excluído
             *     * `queued` - Na Fila de Download
             *     * `downloaded` - Baixado
             */
            curation_status: components["schemas"]["DatasetCurationStatusEnum"];
            /**
             * @description Motivo de exclusão (usado quando curation_status=excluded).
             * @default
             */
            exclusion_reason: string;
        };
        /**
         * @description * `pending` - Pendente
         *     * `included` - Incluído
         *     * `excluded` - Excluído
         *     * `queued` - Na Fila de Download
         *     * `downloaded` - Baixado
         * @enum {string}
         */
        DatasetCurationStatusEnum: "pending" | "included" | "excluded" | "queued" | "downloaded";
        EntityContext: {
            entity_type: components["schemas"]["EntityTypeEnum"];
            /** Nome da Entidade */
            entity_name: string;
            /**
             * Sentença Contexto
             * @description Sentença do abstract contendo a entidade
             */
            sentence: string;
            /**
             * Posição no Abstract
             * @description Índice da sentença no abstract (0-based)
             */
            sentence_position?: number;
        };
        /**
         * @description * `gene` - Gene
         *     * `drug` - Droga
         *     * `variant` - Variante
         *     * `disease` - Doença
         *     * `pathway` - Pathway
         * @enum {string}
         */
        EntityTypeEnum: "gene" | "drug" | "variant" | "disease" | "pathway";
        IngestionJob: {
            /** Format: uuid */
            readonly id: string;
            readonly job_type: components["schemas"]["JobTypeEnum"];
            readonly status: components["schemas"]["IngestionJobStatusEnum"];
            /** @description Query, date range, PMIDs, etc. */
            readonly parameters: unknown;
            readonly records_processed: number;
            readonly records_inserted: number;
            readonly records_updated: number;
            readonly error_message: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly started_at: string | null;
            /** Format: date-time */
            readonly completed_at: string | null;
        };
        /**
         * @description * `pending` - Pendente
         *     * `running` - Executando
         *     * `completed` - Completo
         *     * `failed` - Falhou
         *     * `cancelled` - Cancelado
         * @enum {string}
         */
        IngestionJobStatusEnum: "pending" | "running" | "completed" | "failed" | "cancelled";
        /** @description Resposta de erro quando o job já está em estado terminal. */
        JobCancelError: {
            detail: string;
        };
        /** @description Resposta de ações que despacham um job de ingestão (202 Accepted). */
        JobDispatchResponse: {
            /** Format: uuid */
            job_id: string;
            status: string;
        };
        /**
         * @description * `pubmed_search` - Busca PubMed
         *     * `pubmed_fetch` - Fetch PubMed XML
         *     * `geo_search` - Busca GEO
         *     * `sra_search` - Busca SRA
         *     * `gwas_search` - Busca GWAS Catalog
         *     * `sample_fetch` - Fetch de Amostras
         *     * `variant_annotation` - Anotação de Variantes
         *     * `gene_ner` - Extração de Genes
         *     * `drug_ner` - Extração de Drogas
         *     * `context_extraction` - Extração de Contextos
         * @enum {string}
         */
        JobTypeEnum: "pubmed_search" | "pubmed_fetch" | "geo_search" | "sra_search" | "gwas_search" | "sample_fetch" | "variant_annotation" | "gene_ner" | "drug_ner" | "context_extraction";
        OmicDataset: {
            readonly id: number;
            /** @description GSE, SRP, PRJNA, E-MTAB, etc. */
            accession: string;
            /** Banco de Origem */
            source_db: components["schemas"]["SourceDbEnum"];
            bioproject_id?: string;
            /** Título */
            title: string;
            /** Resumo/Descrição */
            summary?: string;
            /** Tipo Ômico */
            omic_type?: components["schemas"]["OmicTypeEnum"] | components["schemas"]["BlankEnum"];
            /**
             * Subcategoria
             * @description Ex: RNA-Seq, WGS, ChIP-Seq, 16S
             */
            omic_subcategory?: string;
            /** Organismo */
            organism?: string;
            /** Taxonomy ID */
            tax_id?: number | null;
            /** Número de Amostras */
            n_samples?: number | null;
            /**
             * Plataforma
             * @description GPL number ou nome da tecnologia
             */
            platform?: string;
            readonly extra_metadata: Record<string, never>;
            is_active?: boolean;
            /** Format: date-time */
            readonly ingested_at: string;
        };
        /** @description Serializer read-only do dado compartilhado OmicSample. */
        OmicSample: {
            readonly id: number;
            /** @description GSM, SRR, SRS, etc. — chave natural da amostra */
            accession: string;
            /** Título */
            title?: string;
            /** @description Tecido/fonte declarada da amostra (ex: "blood", "tumor biopsy") */
            source_name?: string;
            /** Organismo */
            organism?: string;
            /** Taxonomy ID */
            tax_id?: number | null;
            /**
             * Plataforma
             * @description GPL number ou nome da tecnologia
             */
            platform?: string;
            readonly characteristics: {
                [key: string]: string;
            };
            readonly extra_metadata: Record<string, never>;
            /** Format: date-time */
            readonly ingested_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `genomic` - Genômica
         *     * `transcriptomic` - Transcriptômica
         *     * `proteomic` - Proteômica
         *     * `metabolomic` - Metabolômica
         *     * `epigenomic` - Epigenômica
         *     * `metagenomic` - Metagenômica
         *     * `microbiome` - Microbiômica
         *     * `multi_omic` - Multi-ômica
         *     * `other` - Outro
         * @enum {string}
         */
        OmicTypeEnum: "genomic" | "transcriptomic" | "proteomic" | "metabolomic" | "epigenomic" | "metagenomic" | "microbiome" | "multi_omic" | "other";
        /** @description Body de /projects/{id}/omics_search/ — todos os campos são opcionais. */
        OmicsSearchRequest: {
            /** @description Lista de fontes ômicas (GEO, SRA, BioProject, GWAS). Null = todas. */
            sources?: string[] | null;
            /**
             * @description Máximo de registros por fonte.
             * @default 500
             */
            max_per_source: number;
        };
        PaginatedClinicalCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ClinicalCategory"][];
        };
        PaginatedDaVinciProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DaVinciProject"][];
        };
        PaginatedIngestionJobList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IngestionJob"][];
        };
        PaginatedProjectDatasetListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectDatasetList"][];
        };
        PaginatedProjectPaperDatasetList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectPaperDataset"][];
        };
        PaginatedProjectPaperListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectPaperList"][];
        };
        PaginatedProjectSampleListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectSampleList"][];
        };
        PaginatedUserCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UserCategory"][];
        };
        PaperAuthor: {
            /**
             * Posição na Lista
             * @description 1 = primeiro autor, último = senior author
             */
            position: number;
            /** Sobrenome */
            last_name: string;
            /** Iniciais */
            initials?: string;
            /** Afiliação */
            affiliation?: string;
            /**
             * País
             * @description Extraído da afiliação via regex no Rust
             */
            country?: string;
        };
        /** @description Body de bulk_curate: atualiza curation_status para múltiplos papers. */
        PaperBulkCurateRequest: {
            /** @description Lista de IDs de ProjectPaper a atualizar. */
            paper_ids: number[];
            /**
             * @description Status de curadoria a aplicar.
             *
             *     * `pending` - Pendente
             *     * `included` - Incluído
             *     * `excluded` - Excluído
             *     * `maybe` - Talvez
             */
            curation_status: components["schemas"]["CurationStatusEnum"];
        };
        /** @description Resposta de bulk_curate: quantidade de registros atualizados. */
        PaperBulkCurateResponse: {
            updated: number;
        };
        /** @description Body de categorize: adiciona/remove categorias clínicas e de usuário. */
        PaperCategorizeRequest: {
            /** @description Slugs de categorias clínicas a adicionar. */
            clinical_add?: string[];
            /** @description Slugs de categorias clínicas a remover. */
            clinical_remove?: string[];
            /** @description IDs de UserCategory a adicionar. */
            user_add?: number[];
            /** @description IDs de UserCategory a remover. */
            user_remove?: number[];
        };
        /** @description Full paper detail with all nested entities. */
        PaperDetail: {
            readonly id: number;
            /**
             * PubMed ID
             * Format: int64
             * @description Identificador único no PubMed
             */
            pmid: number;
            pmc_id?: string;
            doi?: string;
            /** Título */
            title: string;
            /** Resumo */
            abstract?: string;
            /** Periódico (ISO) */
            journal?: string;
            /** Ano de Publicação */
            pub_year?: number | null;
            /** Mês de Publicação */
            pub_month?: number | null;
            readonly authors: components["schemas"]["PaperAuthor"][];
            readonly keywords: components["schemas"]["PaperKeyword"][];
            readonly mesh_terms: components["schemas"]["PaperMeSHTerm"][];
            readonly genes: components["schemas"]["PaperGene"][];
            readonly drugs: components["schemas"]["PaperDrug"][];
            readonly variants: components["schemas"]["PaperVariant"][];
            readonly contexts: components["schemas"]["EntityContext"][];
            /** Format: date-time */
            readonly ingested_at: string;
        };
        PaperDrug: {
            /** Nome da Droga */
            drug_name: string;
            /** Menções no Abstract */
            mention_count?: number;
            /** @description Referência cruzada opcional com DrugBank */
            drugbank_id?: string;
        };
        PaperGene: {
            /** Símbolo do Gene */
            gene_symbol: string;
            /**
             * Entrez Gene ID
             * Format: int64
             */
            entrez_id?: number | null;
            /** Menções no Abstract */
            mention_count?: number;
        };
        PaperKeyword: {
            keyword: string;
        };
        PaperMeSHTerm: {
            /** MeSH Descriptor */
            descriptor: string;
            /** MeSH Qualifier */
            qualifier?: string;
            /**
             * Major Topic
             * @description MeSH MajorTopicYN="Y"
             */
            is_major_topic?: boolean;
        };
        PaperVariant: {
            rs_number: string;
        };
        PatchedDaVinciProject: {
            /** Format: uuid */
            readonly id?: string;
            query_synonyms?: string[];
            target_organisms?: string[];
            target_tissues?: string[];
            /** @default 0 */
            readonly total_papers: number;
            /** @default 0 */
            readonly total_datasets: number;
            /**
             * Identificador
             * @description Gerado automaticamente: {titulo}_{user}_davinci
             */
            readonly slug?: string;
            /** Título do Projeto */
            title?: string;
            /** Descrição */
            description?: string;
            /**
             * Termo de Busca Principal
             * @description Ex: "hidradenitis AND cancer", "cardiovascular disease"
             */
            query_term?: string;
            /** Ano Inicial */
            date_from?: number | null;
            /** Ano Final */
            date_to?: number | null;
            readonly status?: components["schemas"]["DaVinciProjectStatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly user?: number;
        };
        /** @description Write-only: update curation fields. */
        PatchedProjectDatasetCurate: {
            curation_status?: components["schemas"]["DatasetCurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
        };
        /** @description Write-only: update curation fields. */
        PatchedProjectPaperCurate: {
            curation_status?: components["schemas"]["CurationStatusEnum"];
            /**
             * Motivo da Exclusão
             * @description Auditável: por que o pesquisador excluiu este paper
             */
            exclusion_reason?: string;
            /** Notas do Pesquisador */
            notes?: string;
            /**
             * Score de Relevância
             * Format: double
             * @description 0.0 a 1.0 — calculado pelo Rust ou ajustado manualmente
             */
            relevance_score?: number | null;
        };
        /** @description Write-only: atualiza apenas campos de curadoria. */
        PatchedProjectSampleCurate: {
            curation_status?: components["schemas"]["CurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
        };
        PatchedUserCategory: {
            readonly id?: number;
            /** Nome da Categoria */
            name?: string;
            /** @description Termos para classificação automática ou manual */
            keywords?: unknown;
            /**
             * Cor (hex)
             * @description Para visualização no frontend
             */
            color?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        /** @description Para atualização de perfil pelo pesquisador. */
        PatchedUserProfileUpdate: {
            /** @description ORCID iD do pesquisador (formato: 0000-0000-0000-0000) */
            orcid_id?: string | null;
            institution?: string;
            research_area?: string;
            first_name?: string;
            last_name?: string;
            /** @description NCBI API Key pessoal (eleva rate limit de 3 para 10 req/s) */
            ncbi_api_key?: string;
        };
        /** @description Write-only: update curation fields. */
        ProjectDatasetCurate: {
            curation_status?: components["schemas"]["DatasetCurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
        };
        /** @description Full detail: dataset content + curation fields. */
        ProjectDatasetDetail: {
            readonly id: number;
            readonly dataset: components["schemas"]["OmicDataset"];
            curation_status?: components["schemas"]["DatasetCurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
            /** Format: date-time */
            readonly added_at: string;
            /** Format: date-time */
            readonly curated_at: string | null;
        };
        /** @description Compact list — includes summary and platform for the detail panel. */
        ProjectDatasetList: {
            readonly id: number;
            readonly accession: string;
            readonly source_db: string;
            readonly bioproject_id: string;
            readonly title: string;
            readonly summary: string;
            readonly omic_type: string;
            readonly omic_subcategory: string;
            readonly organism: string;
            readonly n_samples: number | null;
            readonly platform: string;
            curation_status?: components["schemas"]["DatasetCurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
            /** Format: date-time */
            readonly added_at: string;
            /** Format: date-time */
            curated_at?: string | null;
        };
        /** @description Write-only: update curation fields. */
        ProjectPaperCurate: {
            curation_status?: components["schemas"]["CurationStatusEnum"];
            /**
             * Motivo da Exclusão
             * @description Auditável: por que o pesquisador excluiu este paper
             */
            exclusion_reason?: string;
            /** Notas do Pesquisador */
            notes?: string;
            /**
             * Score de Relevância
             * Format: double
             * @description 0.0 a 1.0 — calculado pelo Rust ou ajustado manualmente
             */
            relevance_score?: number | null;
        };
        ProjectPaperDataset: {
            readonly id: number;
            readonly pmid: number;
            readonly paper_title: string;
            readonly accession: string;
            readonly dataset_title: string;
            readonly omic_type: string;
            confidence?: components["schemas"]["ConfidenceEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Full detail: paper content + curation fields. */
        ProjectPaperDetail: {
            readonly id: number;
            readonly paper: components["schemas"]["PaperDetail"];
            curation_status?: components["schemas"]["CurationStatusEnum"];
            /**
             * Motivo da Exclusão
             * @description Auditável: por que o pesquisador excluiu este paper
             */
            exclusion_reason?: string;
            /** Notas do Pesquisador */
            notes?: string;
            /**
             * Score de Relevância
             * Format: double
             * @description 0.0 a 1.0 — calculado pelo Rust ou ajustado manualmente
             */
            relevance_score?: number | null;
            readonly clinical_categories: components["schemas"]["ClinicalCategoryBrief"][];
            readonly user_categories: components["schemas"]["UserCategoryBrief"][];
            /** Format: date-time */
            readonly added_at: string;
            /**
             * Curado em
             * Format: date-time
             */
            readonly curated_at: string | null;
        };
        /** @description Compact representation for list views — includes abstract for detail panel. */
        ProjectPaperList: {
            readonly id: number;
            readonly pmid: number;
            readonly pmc_id: string;
            readonly doi: string;
            readonly title: string;
            readonly abstract: string;
            readonly journal: string;
            readonly pub_year: number;
            readonly pub_month: number | null;
            readonly pub_type: string;
            curation_status?: components["schemas"]["CurationStatusEnum"];
            /**
             * Motivo da Exclusão
             * @description Auditável: por que o pesquisador excluiu este paper
             */
            exclusion_reason?: string;
            /** Notas do Pesquisador */
            notes?: string;
            /**
             * Score de Relevância
             * Format: double
             * @description 0.0 a 1.0 — calculado pelo Rust ou ajustado manualmente
             */
            relevance_score?: number | null;
            readonly clinical_categories: components["schemas"]["ClinicalCategoryBrief"][];
            readonly user_categories: components["schemas"]["UserCategoryBrief"][];
            /** Format: date-time */
            readonly added_at: string;
            /**
             * Curado em
             * Format: date-time
             */
            curated_at?: string | null;
        };
        /** @description Write-only: atualiza apenas campos de curadoria. */
        ProjectSampleCurate: {
            curation_status?: components["schemas"]["CurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
        };
        /** @description Detalhe completo — sample aninhado + campos de curadoria. */
        ProjectSampleDetail: {
            readonly id: number;
            readonly sample: components["schemas"]["OmicSample"];
            curation_status?: components["schemas"]["CurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
            /** Format: date-time */
            readonly added_at: string;
            /** Format: date-time */
            readonly curated_at: string | null;
        };
        /** @description Lista compacta — campos do sample achatados para evitar N+1 com select_related. */
        ProjectSampleList: {
            readonly id: number;
            readonly accession: string;
            readonly title: string;
            readonly source_name: string;
            readonly organism: string;
            readonly tax_id: number | null;
            readonly platform: string;
            readonly dataset_id: number;
            readonly dataset_accession: string;
            curation_status?: components["schemas"]["CurationStatusEnum"];
            exclusion_reason?: string;
            notes?: string;
            /** Format: double */
            relevance_score?: number | null;
            /** Format: date-time */
            readonly added_at: string;
            /** Format: date-time */
            curated_at?: string | null;
        };
        ProjectStats: {
            readonly total_papers: number;
            readonly included_papers: number;
            readonly excluded_papers: number;
            readonly pending_papers: number;
            readonly total_datasets: number;
            readonly included_datasets: number;
            readonly total_samples: number;
            readonly included_samples: number;
            readonly papers_by_year: {
                [key: string]: number;
            };
            readonly papers_by_journal: {
                [key: string]: number;
            };
            readonly papers_by_country: {
                [key: string]: number;
            };
            readonly papers_by_clinical_category: {
                [key: string]: number;
            };
            readonly datasets_by_omic_type: {
                [key: string]: number;
            };
            readonly datasets_by_organism: {
                [key: string]: number;
            };
            readonly top_genes: {
                gene: string;
                count: number;
            }[];
            readonly top_drugs: {
                drug: string;
                count: number;
            }[];
            readonly top_mesh_terms: {
                term: string;
                count: number;
            }[];
            readonly top_variants: Record<string, never>[];
            /** Format: date-time */
            readonly last_computed: string;
        };
        /** @description Body de bulk_curate de samples. */
        SampleBulkCurateRequest: {
            /** @description Lista de IDs de ProjectSample a atualizar. */
            sample_ids: number[];
            /**
             * @description Status de curadoria a aplicar.
             *
             *     * `pending` - Pendente
             *     * `included` - Incluído
             *     * `excluded` - Excluído
             *     * `maybe` - Talvez
             */
            curation_status: components["schemas"]["CurationStatusEnum"];
            /**
             * @description Motivo de exclusão (usado quando curation_status=excluded).
             * @default
             */
            exclusion_reason: string;
        };
        /**
         * @description * `geo` - GEO (Gene Expression Omnibus)
         *     * `sra` - Sequence Read Archive
         *     * `arrayexpress` - ArrayExpress
         *     * `tcga` - TCGA
         *     * `bioproject` - BioProject
         *     * `gwas_catalog` - GWAS Catalog
         * @enum {string}
         */
        SourceDbEnum: "geo" | "sra" | "arrayexpress" | "tcga" | "bioproject" | "gwas_catalog";
        UserCategory: {
            readonly id: number;
            /** Nome da Categoria */
            name: string;
            /** @description Termos para classificação automática ou manual */
            keywords?: unknown;
            /**
             * Cor (hex)
             * @description Para visualização no frontend
             */
            color?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        UserCategoryBrief: {
            readonly id: number;
            /** Nome da Categoria */
            name: string;
            /**
             * Cor (hex)
             * @description Para visualização no frontend
             */
            color?: string;
        };
        UserProfile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly first_name: string;
            readonly last_name: string;
            /** @description UID do Firebase Authentication */
            readonly firebase_uid: string;
            /** @description Provider usado no login (google.com, password, oidc.orcid) */
            readonly auth_provider: string;
            /** @description ORCID iD do pesquisador (formato: 0000-0000-0000-0000) */
            orcid_id?: string | null;
            institution?: string;
            research_area?: string;
            /** Format: uri */
            avatar_url?: string;
            /** @description NCBI API Key pessoal (eleva rate limit de 3 para 10 req/s) */
            ncbi_api_key?: string;
        };
        _VerifyTokenOk: {
            status: string;
            uid: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserProfileUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserProfileUpdate"];
                "multipart/form-data": components["schemas"]["PatchedUserProfileUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    auth_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_VerifyTokenOk"];
                };
            };
        };
    };
    clinical_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClinicalCategoryList"];
                };
            };
        };
    };
    projects_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDaVinciProjectList"];
                };
            };
        };
    };
    projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaVinciProject"];
                "application/x-www-form-urlencoded": components["schemas"]["DaVinciProject"];
                "multipart/form-data": components["schemas"]["DaVinciProject"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaVinciProject"];
                };
            };
        };
    };
    projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaVinciProject"];
                };
            };
        };
    };
    projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaVinciProject"];
                "application/x-www-form-urlencoded": components["schemas"]["DaVinciProject"];
                "multipart/form-data": components["schemas"]["DaVinciProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaVinciProject"];
                };
            };
        };
    };
    projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDaVinciProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDaVinciProject"];
                "multipart/form-data": components["schemas"]["PatchedDaVinciProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaVinciProject"];
                };
            };
        };
    };
    projects_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV com papers incluídos (quando export_format=csv) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_omics_search_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OmicsSearchRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OmicsSearchRequest"];
                "multipart/form-data": components["schemas"]["OmicsSearchRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDispatchResponse"];
                };
            };
        };
    };
    projects_search_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDispatchResponse"];
                };
            };
        };
    };
    projects_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this da vinci project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStats"];
                };
            };
        };
    };
    projects_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserCategoryList"];
                };
            };
        };
    };
    projects_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCategory"];
                "multipart/form-data": components["schemas"]["UserCategory"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCategory"];
                };
            };
        };
    };
    projects_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserCategory"];
                "multipart/form-data": components["schemas"]["PatchedUserCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCategory"];
                };
            };
        };
    };
    projects_datasets_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectDatasetListList"];
                };
            };
        };
    };
    projects_datasets_samples_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                dataset_pk: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectSampleListList"];
                };
            };
        };
    };
    projects_datasets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDatasetDetail"];
                };
            };
        };
    };
    projects_datasets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectDatasetCurate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectDatasetCurate"];
                "multipart/form-data": components["schemas"]["PatchedProjectDatasetCurate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDatasetCurate"];
                };
            };
        };
    };
    projects_datasets_bulk_curate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetBulkCurateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DatasetBulkCurateRequest"];
                "multipart/form-data": components["schemas"]["DatasetBulkCurateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkCurateResponse"];
                };
            };
        };
    };
    projects_datasets_search_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectDatasetListList"];
                };
            };
        };
    };
    projects_jobs_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngestionJobList"];
                };
            };
        };
    };
    projects_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJob"];
                };
            };
        };
    };
    projects_jobs_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJob"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCancelError"];
                };
            };
        };
    };
    projects_links_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectPaperDatasetList"];
                };
            };
        };
    };
    projects_links_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaperDataset"];
                };
            };
        };
    };
    projects_links_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaperDataset"];
                };
            };
        };
    };
    projects_papers_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectPaperListList"];
                };
            };
        };
    };
    projects_papers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaperDetail"];
                };
            };
        };
    };
    projects_papers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectPaperCurate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectPaperCurate"];
                "multipart/form-data": components["schemas"]["PatchedProjectPaperCurate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaperCurate"];
                };
            };
        };
    };
    projects_papers_categorize_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PaperCategorizeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaperCategorizeRequest"];
                "multipart/form-data": components["schemas"]["PaperCategorizeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaperDetail"];
                };
            };
        };
    };
    projects_papers_bulk_curate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperBulkCurateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaperBulkCurateRequest"];
                "multipart/form-data": components["schemas"]["PaperBulkCurateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperBulkCurateResponse"];
                };
            };
        };
    };
    projects_papers_search_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectPaperListList"];
                };
            };
        };
    };
    projects_samples_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectSampleListList"];
                };
            };
        };
    };
    projects_samples_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSampleDetail"];
                };
            };
        };
    };
    projects_samples_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectSampleCurate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectSampleCurate"];
                "multipart/form-data": components["schemas"]["PatchedProjectSampleCurate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSampleCurate"];
                };
            };
        };
    };
    projects_samples_bulk_curate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleBulkCurateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SampleBulkCurateRequest"];
                "multipart/form-data": components["schemas"]["SampleBulkCurateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkCurateResponse"];
                };
            };
        };
    };
}
