# Generated by Django 6.0.3 on 2026-03-23 14:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('keywords', models.JSONField(default=list, help_text='Termos usados pelo Rust para detectar esta categoria no abstract', verbose_name='Keywords de Classificação')),
                ('is_default', models.BooleanField(default=False, help_text='True para os 5 eixos padrão (não deletável)', verbose_name='Categoria Padrão')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Prioridade')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical categories',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='OmicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omic_type', models.CharField(choices=[('genomic', 'Genômica'), ('transcriptomic', 'Transcriptômica'), ('proteomic', 'Proteômica'), ('metabolomic', 'Metabolômica'), ('epigenomic', 'Epigenômica'), ('metagenomic', 'Metagenômica'), ('microbiome', 'Microbiômica'), ('multi_omic', 'Multi-ômica'), ('other', 'Outro')], max_length=50, unique=True, verbose_name='Tipo Ômico')),
                ('keywords', models.JSONField(default=list, help_text='Lista de termos usados pelo Rust para categorizar datasets', verbose_name='Keywords de Classificação')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Prioridade')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='OmicDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, help_text='GSE, SRP, PRJNA, E-MTAB, etc.', max_length=50, unique=True, verbose_name='Accession')),
                ('source_db', models.CharField(choices=[('geo', 'GEO (Gene Expression Omnibus)'), ('sra', 'Sequence Read Archive'), ('arrayexpress', 'ArrayExpress'), ('tcga', 'TCGA'), ('bioproject', 'BioProject'), ('gwas_catalog', 'GWAS Catalog')], max_length=20, verbose_name='Banco de Origem')),
                ('bioproject_id', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='BioProject ID')),
                ('title', models.TextField(verbose_name='Título')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Resumo/Descrição')),
                ('omic_type', models.CharField(blank=True, choices=[('genomic', 'Genômica'), ('transcriptomic', 'Transcriptômica'), ('proteomic', 'Proteômica'), ('metabolomic', 'Metabolômica'), ('epigenomic', 'Epigenômica'), ('metagenomic', 'Metagenômica'), ('microbiome', 'Microbiômica'), ('multi_omic', 'Multi-ômica'), ('other', 'Outro')], default='', max_length=20, verbose_name='Tipo Ômico')),
                ('omic_subcategory', models.CharField(blank=True, default='', help_text='Ex: RNA-Seq, WGS, ChIP-Seq, 16S', max_length=200, verbose_name='Subcategoria')),
                ('organism', models.CharField(blank=True, default='', max_length=200, verbose_name='Organismo')),
                ('tax_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taxonomy ID')),
                ('n_samples', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Amostras')),
                ('platform', models.CharField(blank=True, default='', help_text='GPL number ou nome da tecnologia', max_length=200, verbose_name='Plataforma')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, help_text='Campos específicos da fonte que não justificam colunas próprias', verbose_name='Metadados Extras')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('rs_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RS Number')),
                ('gene_symbol', models.CharField(blank=True, default='', max_length=50, verbose_name='Gene')),
                ('gene_name', models.TextField(blank=True, default='', verbose_name='Nome do Gene')),
                ('entrez_id', models.BigIntegerField(blank=True, null=True, verbose_name='Entrez ID')),
                ('chromosome', models.CharField(blank=True, default='', max_length=10, verbose_name='Cromossomo')),
                ('position', models.BigIntegerField(blank=True, null=True, verbose_name='Posição')),
                ('alleles', models.CharField(blank=True, default='', max_length=200, verbose_name='Alelos')),
                ('maf', models.FloatField(blank=True, null=True, verbose_name='Minor Allele Frequency')),
                ('clinical_significance', models.CharField(blank=True, default='', max_length=255, verbose_name='Significância Clínica')),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaVinciProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Gerado automaticamente: {titulo}_{user}_davinci', max_length=255, unique=True, verbose_name='Identificador')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Projeto')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('query_term', models.CharField(help_text='Ex: "hidradenitis AND cancer", "cardiovascular disease"', max_length=500, verbose_name='Termo de Busca Principal')),
                ('query_synonyms', models.JSONField(blank=True, default=list, help_text='Termos alternativos para normalização entre bases (PubMed, GEO, SRA)', verbose_name='Sinônimos de Busca')),
                ('date_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Inicial')),
                ('date_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Final')),
                ('target_organisms', models.JSONField(blank=True, default=list, help_text='Ex: ["Homo sapiens", "Mus musculus"]', verbose_name='Organismos Alvo')),
                ('target_tissues', models.JSONField(blank=True, default=list, help_text='Ex: ["blood", "skin", "liver"]', verbose_name='Tecidos Alvo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('searching', 'Buscando'), ('curating', 'Em Curadoria'), ('analyzing', 'Analisando'), ('complete', 'Completo')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davinci_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Completo'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Query, date range, PMIDs, etc.')),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_inserted', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='core.davinciproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetPaperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_source', models.CharField(default='elink', help_text='elink, geo_xml, manual', max_length=50, verbose_name='Origem do Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.omicdataset')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.BigIntegerField(db_index=True, help_text='Identificador único no PubMed', unique=True, verbose_name='PubMed ID')),
                ('pmc_id', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='PMC ID')),
                ('doi', models.CharField(blank=True, default='', max_length=255, verbose_name='DOI')),
                ('title', models.TextField(verbose_name='Título')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='Resumo')),
                ('journal', models.CharField(blank=True, default='', max_length=255, verbose_name='Periódico (ISO)')),
                ('pub_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('pub_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mês de Publicação')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('raw_xml_hash', models.CharField(blank=True, default='', help_text='SHA-256 do XML do PubMed para detectar atualizações', max_length=64, verbose_name='Hash do XML original')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_paper_search__c69629_gin'), models.Index(fields=['pub_year'], name='core_paper_pub_yea_8ea2da_idx'), models.Index(fields=['journal'], name='core_paper_journal_8f21fc_idx')],
            },
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='related_pmids',
            field=models.ManyToManyField(blank=True, related_name='related_datasets', through='core.DatasetPaperLink', to='core.paper'),
        ),
        migrations.CreateModel(
            name='EntityContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('gene', 'Gene'), ('drug', 'Droga'), ('variant', 'Variante'), ('disease', 'Doença'), ('pathway', 'Pathway')], max_length=20)),
                ('entity_name', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Entidade')),
                ('sentence', models.TextField(help_text='Sentença do abstract contendo a entidade', verbose_name='Sentença Contexto')),
                ('sentence_position', models.PositiveSmallIntegerField(default=0, help_text='Índice da sentença no abstract (0-based)', verbose_name='Posição no Abstract')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='core.paper')),
            ],
        ),
        migrations.AddField(
            model_name='datasetpaperlink',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paper'),
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='1 = primeiro autor, último = senior author', verbose_name='Posição na Lista')),
                ('last_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('initials', models.CharField(blank=True, default='', max_length=20, verbose_name='Iniciais')),
                ('affiliation', models.TextField(blank=True, default='', verbose_name='Afiliação')),
                ('country', models.CharField(blank=True, default='', help_text='Extraído da afiliação via regex no Rust', max_length=100, verbose_name='País')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='core.paper')),
            ],
            options={
                'ordering': ['paper', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PaperDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Droga')),
                ('drug_name_lower', models.CharField(db_index=True, help_text='Lowercase para dedup e busca', max_length=255, verbose_name='Nome Normalizado')),
                ('mention_count', models.PositiveIntegerField(default=1, verbose_name='Menções no Abstract')),
                ('drugbank_id', models.CharField(blank=True, default='', help_text='Referência cruzada opcional com DrugBank', max_length=20, verbose_name='DrugBank ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, max_length=50, verbose_name='Símbolo do Gene')),
                ('entrez_id', models.BigIntegerField(blank=True, null=True, verbose_name='Entrez Gene ID')),
                ('mention_count', models.PositiveIntegerField(default=1, verbose_name='Menções no Abstract')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Keyword')),
                ('keyword_lower', models.CharField(db_index=True, help_text='Lowercase para dedup e busca', max_length=255, verbose_name='Keyword Normalizada')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperMeSHTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(db_index=True, max_length=255, verbose_name='MeSH Descriptor')),
                ('qualifier', models.CharField(blank=True, default='', max_length=255, verbose_name='MeSH Qualifier')),
                ('is_major_topic', models.BooleanField(default=False, help_text='MeSH MajorTopicYN="Y"', verbose_name='Major Topic')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_terms', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_number', models.CharField(db_index=True, max_length=20, verbose_name='RS Number')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_status', models.CharField(choices=[('pending', 'Pendente'), ('included', 'Incluído'), ('excluded', 'Excluído'), ('queued', 'Na Fila de Download'), ('downloaded', 'Baixado')], default='pending', max_length=20)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('curated_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_projects', to='core.omicdataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_datasets', to='core.davinciproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_status', models.CharField(choices=[('pending', 'Pendente'), ('included', 'Incluído'), ('excluded', 'Excluído'), ('maybe', 'Talvez')], default='pending', max_length=20)),
                ('exclusion_reason', models.CharField(blank=True, default='', help_text='Auditável: por que o pesquisador excluiu este paper', max_length=500, verbose_name='Motivo da Exclusão')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas do Pesquisador')),
                ('relevance_score', models.FloatField(blank=True, help_text='0.0 a 1.0 — calculado pelo Rust ou ajustado manualmente', null=True, verbose_name='Score de Relevância')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('curated_at', models.DateTimeField(blank=True, null=True, verbose_name='Curado em')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_projects', to='core.paper')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_papers', to='core.davinciproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPaperClinicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0 a 1.0 — automático (Rust) ou 1.0 se manual', verbose_name='Score de Confiança')),
                ('is_manual', models.BooleanField(default=False, help_text='True se o pesquisador atribuiu manualmente', verbose_name='Classificação Manual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinicalcategory')),
                ('project_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='core.projectpaper')),
            ],
        ),
        migrations.AddField(
            model_name='projectpaper',
            name='clinical_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias clínicas atribuídas ao paper (diagnosis, treatment, etc.)', through='core.ProjectPaperClinicalCategory', to='core.clinicalcategory'),
        ),
        migrations.CreateModel(
            name='ProjectPaperDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('auto', 'Automático (elink/co-ocorrência)'), ('confirmed', 'Confirmado pelo Pesquisador'), ('rejected', 'Rejeitado pelo Pesquisador')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.davinciproject')),
                ('project_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectdataset')),
                ('project_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectpaper')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_papers', models.PositiveIntegerField(default=0)),
                ('included_papers', models.PositiveIntegerField(default=0)),
                ('excluded_papers', models.PositiveIntegerField(default=0)),
                ('pending_papers', models.PositiveIntegerField(default=0)),
                ('total_datasets', models.PositiveIntegerField(default=0)),
                ('included_datasets', models.PositiveIntegerField(default=0)),
                ('total_samples', models.PositiveIntegerField(default=0)),
                ('papers_by_year', models.JSONField(blank=True, default=dict)),
                ('papers_by_journal', models.JSONField(blank=True, default=dict)),
                ('papers_by_country', models.JSONField(blank=True, default=dict, help_text='Distribuição geográfica (extraída de PaperAuthor.country)')),
                ('papers_by_clinical_category', models.JSONField(blank=True, default=dict, help_text='Contagem por categoria clínica (diagnosis, treatment, etc.)')),
                ('datasets_by_omic_type', models.JSONField(blank=True, default=dict)),
                ('datasets_by_organism', models.JSONField(blank=True, default=dict)),
                ('top_genes', models.JSONField(blank=True, default=list, help_text='Top N genes mencionados na literatura do projeto')),
                ('top_drugs', models.JSONField(blank=True, default=list, help_text='Top N drogas/fármacos mencionados na literatura do projeto')),
                ('top_mesh_terms', models.JSONField(blank=True, default=list, help_text='Top N MeSH terms na literatura do projeto')),
                ('top_variants', models.JSONField(blank=True, default=list)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.davinciproject')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('keywords', models.JSONField(default=list, help_text='Termos para classificação automática ou manual', verbose_name='Keywords')),
                ('color', models.CharField(blank=True, default='', help_text='Para visualização no frontend', max_length=7, verbose_name='Cor (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='core.davinciproject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectpaper',
            name='user_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias customizadas do pesquisador para este projeto', to='core.usercategory'),
        ),
        migrations.AddIndex(
            model_name='davinciproject',
            index=models.Index(fields=['user', 'status'], name='core_davinc_user_id_d2e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='davinciproject',
            index=models.Index(fields=['query_term'], name='core_davinc_query_t_ed1ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['project', 'status'], name='core_ingest_project_9c46bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['job_type', 'status'], name='core_ingest_job_typ_6222dc_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_omicda_search__ce7227_gin'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['omic_type'], name='core_omicda_omic_ty_033cae_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['organism'], name='core_omicda_organis_4279cf_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['source_db'], name='core_omicda_source__659119_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['n_samples'], name='core_omicda_n_sampl_771e19_idx'),
        ),
        migrations.AddIndex(
            model_name='entitycontext',
            index=models.Index(fields=['entity_type', 'entity_name'], name='core_entity_entity__7ccd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='entitycontext',
            index=models.Index(fields=['paper', 'entity_type'], name='core_entity_paper_i_ccaa60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetpaperlink',
            unique_together={('dataset', 'paper')},
        ),
        migrations.AddIndex(
            model_name='paperauthor',
            index=models.Index(fields=['last_name'], name='core_papera_last_na_3a02e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paperauthor',
            index=models.Index(fields=['country'], name='core_papera_country_c79b9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperauthor',
            unique_together={('paper', 'position')},
        ),
        migrations.AddIndex(
            model_name='paperdrug',
            index=models.Index(fields=['drug_name_lower'], name='core_paperd_drug_na_b8fae2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperdrug',
            unique_together={('paper', 'drug_name_lower')},
        ),
        migrations.AddIndex(
            model_name='papergene',
            index=models.Index(fields=['entrez_id'], name='core_paperg_entrez__4e8df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='papergene',
            unique_together={('paper', 'gene_symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='paperkeyword',
            unique_together={('paper', 'keyword_lower')},
        ),
        migrations.AddIndex(
            model_name='papermeshterm',
            index=models.Index(fields=['descriptor', 'is_major_topic'], name='core_paperm_descrip_c6f9da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='papermeshterm',
            unique_together={('paper', 'descriptor', 'qualifier')},
        ),
        migrations.AlterUniqueTogether(
            name='papervariant',
            unique_together={('paper', 'rs_number')},
        ),
        migrations.AddIndex(
            model_name='projectdataset',
            index=models.Index(fields=['project', 'curation_status'], name='core_projec_project_c139d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdataset',
            unique_together={('project', 'dataset')},
        ),
        migrations.AlterUniqueTogether(
            name='projectpaperclinicalcategory',
            unique_together={('project_paper', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='projectpaperdataset',
            unique_together={('project', 'project_paper', 'project_dataset')},
        ),
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='projectpaper',
            index=models.Index(fields=['project', 'curation_status'], name='core_projec_project_79a332_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpaper',
            index=models.Index(fields=['relevance_score'], name='core_projec_relevan_2621e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpaper',
            unique_together={('project', 'paper')},
        ),
    ]
