# Generated by Django 6.0.3 on 2026-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paper_pub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omicdataset',
            name='omic_type',
            field=models.CharField(blank=True, choices=[('genomic', 'Genômica'), ('transcriptomic', 'Transcriptômica'), ('proteomic', 'Proteômica'), ('metabolomic', 'Metabolômica'), ('epigenomic', 'Epigenômica'), ('metagenomic', 'Metagenômica'), ('microbiome', 'Microbiômica'), ('multi_omic', 'Multi-ômica'), ('other', 'Outro')], default='', max_length=200, verbose_name='Tipo Ômico'),
        ),
    ]
