# Generated by Django 6.0.3 on 2026-04-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_omicdataset_omic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstats',
            name='omic_subcategory',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='omicdataset',
            name='omic_subcategory',
            field=models.CharField(blank=True, default='', help_text='Ex: RNA-Seq, WGS, ChIP-Seq, 16S', max_length=500, verbose_name='Subcategoria'),
        ),
    ]
