# Generated by Django 6.0.3 on 2026-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_datasetpaperlinkpending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpaperlinkpending',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
