# Generated by Django 6.0.3 on 2026-06-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_datasetpaperlinkpending_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstats',
            name='included_samples',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OmicSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, help_text='GSM, SRR, SRS, etc. — chave natural da amostra', max_length=50, unique=True, verbose_name='Accession')),
                ('title', models.TextField(blank=True, default='', verbose_name='Título')),
                ('source_name', models.CharField(blank=True, default='', help_text='Tecido/fonte declarada da amostra (ex: "blood", "tumor biopsy")', max_length=500, verbose_name='Source Name')),
                ('organism', models.CharField(blank=True, default='', max_length=200, verbose_name='Organismo')),
                ('tax_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taxonomy ID')),
                ('platform', models.CharField(blank=True, default='', help_text='GPL number ou nome da tecnologia', max_length=200, verbose_name='Plataforma')),
                ('characteristics', models.JSONField(blank=True, default=dict, help_text='Metadados key/value da amostra (ex: {"age": "45", "sex": "F"})', verbose_name='Características')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, help_text='Campos específicos da fonte que não justificam colunas próprias', verbose_name='Metadados Extras')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.omicdataset')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_status', models.CharField(choices=[('pending', 'Pendente'), ('included', 'Incluído'), ('excluded', 'Excluído'), ('maybe', 'Talvez')], default='pending', max_length=20)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('curated_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='core.davinciproject')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_projects', to='core.omicsample')),
            ],
        ),
        migrations.AddIndex(
            model_name='omicsample',
            index=models.Index(fields=['dataset'], name='core_omicsa_dataset_81f56e_idx'),
        ),
        migrations.AddIndex(
            model_name='omicsample',
            index=models.Index(fields=['accession'], name='core_omicsa_accessi_a966af_idx'),
        ),
        migrations.AddIndex(
            model_name='omicsample',
            index=models.Index(fields=['organism'], name='core_omicsa_organis_38a62a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsample',
            index=models.Index(fields=['project', 'curation_status'], name='core_projec_project_f4ee12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsample',
            unique_together={('project', 'sample')},
        ),
    ]
