# Generated by Django 6.0.3 on 2026-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projectstats_included_samples_omicsample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos')], max_length=30),
        ),
    ]
