# Generated by Django 6.0.3 on 2026-06-19 08:30

from django.db import migrations, models


def dedup_entity_context(apps, schema_editor):
    """
    Dedup defensivo antes da unique_together. A tabela aparenta estar
    vazia hoje (não populada por Rust), mas se houver duplicatas em
    (paper, entity_type, entity_name, sentence_position), mantém a de
    menor id e remove as demais para que AlterUniqueTogether não falhe.
    Idempotente; reverso é no-op (constraint nova não cria duplicatas).
    """
    EntityContext = apps.get_model('core', 'EntityContext')
    from django.db.models import Count, Min

    dup_keys = (
        EntityContext.objects
        .values('paper', 'entity_type', 'entity_name', 'sentence_position')
        .annotate(n=Count('id'), keep=Min('id'))
        .filter(n__gt=1)
    )
    for key in dup_keys:
        (
            EntityContext.objects
            .filter(
                paper=key['paper'],
                entity_type=key['entity_type'],
                entity_name=key['entity_name'],
                sentence_position=key['sentence_position'],
            )
            .exclude(id=key['keep'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ingestionjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitycontext',
            name='computed_at',
            field=models.DateTimeField(blank=True, help_text='Momento em que o snippet foi derivado/materializado. Comparar com paper.updated_at para invalidar cache stale.', null=True, verbose_name='Derivado em'),
        ),
        migrations.RunPython(
            dedup_entity_context,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='entitycontext',
            unique_together={('paper', 'entity_type', 'entity_name', 'sentence_position')},
        ),
        migrations.AddIndex(
            model_name='entitycontext',
            index=models.Index(fields=['paper', 'entity_type', 'entity_name'], name='core_entity_paper_i_c43a6f_idx'),
        ),
    ]
