# Generated by Django 6.0.3 on 2026-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entitycontext_computed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycontext',
            name='sentence_position',
            field=models.SmallIntegerField(default=0, help_text='Índice da sentença no abstract (0-based; -1 = sentinela "processado sem snippet")', verbose_name='Posição no Abstract'),
        ),
    ]
