# Generated by Django 6.0.3 on 2026-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_entitycontext_sentence_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycontext',
            name='entity_type',
            field=models.CharField(choices=[('gene', 'Gene'), ('drug', 'Droga'), ('variant', 'Variante'), ('disease', 'Doença'), ('pathway', 'Pathway'), ('mesh', 'MeSH Term')], max_length=20),
        ),
    ]
