# Generated by Django 6.0.3 on 2026-06-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_entitycontext_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='davinciproject',
            name='advanced_search_enabled',
            field=models.BooleanField(default=False, verbose_name='Pesquisa Avançada Habilitada'),
        ),
        migrations.AddField(
            model_name='davinciproject',
            name='magnitude_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Último preview de magnitude calculado', verbose_name='Snapshot de Magnitude'),
        ),
        migrations.AddField(
            model_name='davinciproject',
            name='mesh_default_mode',
            field=models.CharField(default='and', help_text="'and' (precisão) ou 'or' (recall)", max_length=3, verbose_name='Modo Padrão MeSH'),
        ),
        migrations.AddField(
            model_name='davinciproject',
            name='selected_mesh',
            field=models.JSONField(blank=True, default=list, help_text='[{"descriptor": str, "ui": str, "qualifiers": [str], "mode": "and"|"or", "major_only": bool}]', verbose_name='Descritores MeSH Selecionados'),
        ),
    ]
