# Generated by Django 6.0.3 on 2026-06-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_davinciproject_advanced_search_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papervariant',
            name='mention_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Menções no Abstract'),
        ),
    ]
