# Generated by Django 6.0.3 on 2026-06-19 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_papervariant_mention_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos'), ('geo_supplementary_download', 'Download Suplementar GEO'), ('fastq_download', 'Download FASTQ')], max_length=30),
        ),
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, help_text='Chave natural estável (ex.: GSExxx_supp_<nome>, SRRxxx_1)', max_length=255, unique=True, verbose_name='Accession')),
                ('file_type', models.CharField(choices=[('series_matrix', 'Series Matrix (GEO)'), ('supplementary', 'Suplementar (GEO)'), ('cel', 'CEL (Affymetrix)'), ('fastq', 'FASTQ (reads brutos)'), ('sra', 'SRA')], max_length=20, verbose_name='Tipo de Arquivo')),
                ('source', models.CharField(choices=[('geo_ftp', 'GEO FTP (NCBI)'), ('ena_ftp', 'ENA FTP'), ('sra_tools', 'sra-tools')], max_length=20, verbose_name='Fonte')),
                ('remote_url', models.TextField(verbose_name='URL Remota')),
                ('storage_key', models.TextField(blank=True, default='', help_text='Path no object storage; vazio até o download concluir', verbose_name='Storage Key')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('checksum_md5', models.CharField(blank=True, max_length=128, null=True, verbose_name='Checksum MD5')),
                ('checksum_algo', models.CharField(default='md5', max_length=20, verbose_name='Algoritmo de Checksum')),
                ('download_status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na Fila'), ('downloading', 'Baixando'), ('downloaded', 'Baixado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20, verbose_name='Status do Download')),
                ('bytes_downloaded', models.BigIntegerField(default=0, help_text='Progresso/retomada (Range request)', verbose_name='Bytes Baixados')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Baixado em')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.omicdataset')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.omicsample')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dataset__isnull', False), ('sample__isnull', True)), models.Q(('dataset__isnull', True), ('sample__isnull', False)), _connector='OR'), name='datasetfile_dataset_xor_sample')],
            },
        ),
    ]
