# Generated by Django 6.0.3 on 2026-06-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ingestionjob_job_type_datasetfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdataset',
            name='ingestion_job',
            field=models.ForeignKey(blank=True, help_text='Job de ingestão que criou este vínculo (proveniência da busca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datasets', to='core.ingestionjob'),
        ),
        migrations.AddField(
            model_name='projectpaper',
            name='ingestion_job',
            field=models.ForeignKey(blank=True, help_text='Job de ingestão que criou este vínculo (proveniência da busca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_papers', to='core.ingestionjob'),
        ),
        migrations.AddIndex(
            model_name='projectdataset',
            index=models.Index(fields=['project', 'ingestion_job'], name='core_projec_project_cb8049_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpaper',
            index=models.Index(fields=['project', 'ingestion_job'], name='core_projec_project_fe9805_idx'),
        ),
    ]
