# Generated by Django 6.0.3 on 2026-06-20 19:29

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_projectdataset_ingestion_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omicdataset',
            name='access_type',
            field=models.CharField(choices=[('public', 'Público'), ('controlled', 'Controlado'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Tipo de Acesso'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='contract_confidence',
            field=models.JSONField(blank=True, default=dict, help_text='{eixo: score 0..1}, populado nas Fases 2/3', verbose_name='Confiança do Contrato'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='data_format',
            field=models.CharField(choices=[('raw', 'Bruto (raw)'), ('processed', 'Processado'), ('unknown', 'Desconhecido')], default='unknown', max_length=15, verbose_name='Formato dos Dados'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='disease_axis',
            field=models.CharField(choices=[('monogenic', 'Monogênica'), ('multifactorial', 'Multifatorial'), ('indeterminate', 'Indeterminado')], default='indeterminate', max_length=15, verbose_name='Eixo da Doença'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='has_control_group',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('unknown', 'Desconhecido')], default='unknown', max_length=10, verbose_name='Tem grupo controle?'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='is_single_cell',
            field=models.CharField(choices=[('single_cell', 'Single-cell'), ('bulk', 'Bulk'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Single-cell?'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='omics_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nº de camadas ômicas distintas. NULL = não avaliado', null=True, verbose_name='Nº de Camadas Ômicas'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='omics_layers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Camadas ômicas normalizadas (genomic, transcriptomic, ...)'),
        ),
        migrations.AddField(
            model_name='omicdataset',
            name='sample_join_key',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Chaves de junção entre datasets (N chaves). [] = ausente'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['omics_layers'], name='omicdataset_layers_gin'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sample_join_key'], name='omicdataset_join_key_gin'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['is_single_cell'], name='omicdataset_single_cell_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['has_control_group'], name='omicdataset_control_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['disease_axis'], name='omicdataset_disease_axis_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['data_format'], name='omicdataset_data_format_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['access_type'], name='omicdataset_access_type_idx'),
        ),
        migrations.AddIndex(
            model_name='omicdataset',
            index=models.Index(fields=['omics_count'], name='omicdataset_omics_count_idx'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('is_single_cell__in', ['single_cell', 'bulk', 'unknown'])), name='omicdataset_is_single_cell_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('has_control_group__in', ['yes', 'no', 'unknown'])), name='omicdataset_has_control_group_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('disease_axis__in', ['monogenic', 'multifactorial', 'indeterminate'])), name='omicdataset_disease_axis_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('data_format__in', ['raw', 'processed', 'unknown'])), name='omicdataset_data_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('access_type__in', ['public', 'controlled', 'unknown'])), name='omicdataset_access_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('omics_layers__contained_by', ['genomic', 'transcriptomic', 'proteomic', 'metabolomic', 'epigenomic', 'metagenomic', 'microbiome'])), name='omicdataset_omics_layers_valid'),
        ),
    ]
