# Generated by Django 6.0.3 on 2026-06-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_omicdataset_contract_db_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, max_length=50, verbose_name='Símbolo do Gene')),
                ('entrez_id', models.BigIntegerField(blank=True, null=True, verbose_name='Entrez Gene ID')),
                ('mention_count', models.PositiveIntegerField(default=1, verbose_name='Menções')),
                ('source', models.CharField(choices=[('paper_link', 'Paper Vinculado'), ('dataset_metadata', 'Metadados do Dataset')], db_index=True, max_length=20, verbose_name='Procedência')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='core.omicdataset')),
            ],
            options={
                'indexes': [models.Index(fields=['entrez_id'], name='core_datase_entrez__ae4c23_idx'), models.Index(fields=['dataset', 'gene_symbol'], name='core_datase_dataset_fb4375_idx')],
                'unique_together': {('dataset', 'gene_symbol', 'source')},
            },
        ),
    ]
