# Generated by Django 6.0.3 on 2026-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_datasetgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAxisReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nome cru, exatamente como veio da fonte.', max_length=512, verbose_name='Nome da Doença/Trait')),
                ('name_normalized', models.CharField(db_index=True, help_text='Lowercase/limpo, usado como alvo do fuzzy name-matching.', max_length=512, verbose_name='Nome Normalizado')),
                ('axis', models.CharField(choices=[('monogenic', 'Monogênica'), ('multifactorial', 'Multifatorial')], db_index=True, help_text='monogenic ou multifactorial — qual eixo esta entrada ancora.', max_length=20, verbose_name='Eixo Ancorado')),
                ('source', models.CharField(choices=[('gwas_catalog', 'GWAS Catalog'), ('orphanet', 'Orphanet'), ('g2p', 'Gene2Phenotype')], db_index=True, max_length=20, verbose_name='Fonte')),
                ('source_version', models.CharField(blank=True, default='', help_text='Identificador do release (ex.: data do FTP do GWAS Catalog).', max_length=100, verbose_name='Versão/Release da Fonte')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Carregado em')),
            ],
            options={
                'verbose_name': 'Disease axis reference',
                'verbose_name_plural': 'Disease axis references',
                'indexes': [models.Index(fields=['axis', 'name_normalized'], name='diseaseaxisref_axis_norm_idx')],
                'unique_together': {('source', 'name')},
            },
        ),
    ]
