# Generated by Django 6.0.3 on 2026-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_diseaseaxisreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MendelianGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, help_text='UPPERCASE normalizado — casa por igualdade exata com DatasetGene.gene_symbol no cross do monogenic_gene_hit.', max_length=50, verbose_name='Símbolo do Gene')),
                ('entrez_id', models.BigIntegerField(blank=True, help_text='Xref estável quando disponível.', null=True, verbose_name='Entrez Gene ID')),
                ('hgnc_id', models.CharField(blank=True, default='', help_text='Ex.: "HGNC:6614". G2P fornece direto; Orphanet via xref.', max_length=32, verbose_name='HGNC ID')),
                ('ensembl_id', models.CharField(blank=True, default='', help_text='Ex.: "ENSG00000166813". Orphanet fornece via ExternalReference.', max_length=32, verbose_name='Ensembl Gene ID')),
                ('disease_name', models.CharField(blank=True, default='', help_text='Doença associada ao gene na fonte — rastreabilidade da fila de curadoria de alto valor.', max_length=512, verbose_name='Doença Monogênica Associada')),
                ('source', models.CharField(choices=[('orphanet', 'Orphanet'), ('g2p', 'Gene2Phenotype')], db_index=True, max_length=20, verbose_name='Fonte')),
                ('confidence', models.CharField(choices=[('definitive', 'Definitive'), ('strong', 'Strong'), ('moderate', 'Moderate'), ('limited', 'Limited'), ('assessed', 'Assessed'), ('not_assessed', 'Not assessed'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Escala ordinal comparável que pondera o monogenic_gene_hit.', max_length=20, verbose_name='Confiança (normalizada)')),
                ('confidence_raw', models.CharField(blank=True, default='', help_text='Valor original (G2P confidence ou tipo de associação Orphanet) antes da normalização — auditoria.', max_length=128, verbose_name='Confiança (crua da fonte)')),
                ('source_version', models.CharField(blank=True, default='', help_text='Release: Orphanet date/version do <JDBOR>; G2P Last-Modified.', max_length=100, verbose_name='Versão/Release da Fonte')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Carregado em')),
            ],
            options={
                'verbose_name': 'Mendelian gene',
                'verbose_name_plural': 'Mendelian genes',
                'indexes': [models.Index(fields=['gene_symbol'], name='mendgene_symbol_idx'), models.Index(fields=['gene_symbol', 'source'], name='mendgene_symbol_source_idx')],
                'unique_together': {('source', 'gene_symbol', 'disease_name')},
            },
        ),
    ]
