# Generated by Django 6.0.3 on 2026-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mendeliangene'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='omicdataset',
            name='omicdataset_disease_axis_valid',
        ),
        migrations.AlterField(
            model_name='omicdataset',
            name='disease_axis',
            field=models.CharField(choices=[('monogenic', 'Monogênica'), ('multifactorial', 'Multifatorial'), ('mixed', 'Mista'), ('indeterminate', 'Indeterminado')], default='indeterminate', max_length=15, verbose_name='Eixo da Doença'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('disease_axis__in', ['monogenic', 'multifactorial', 'mixed', 'indeterminate'])), name='omicdataset_disease_axis_valid'),
        ),
    ]
