# Generated by Django 6.0.3 on 2026-06-23 08:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_sra_runs(apps, schema_editor):
    """
    Migra a aresta GEO→SRA de OmicSample.extra_metadata['sra_runs'] (JSON)
    para linhas SampleSraRun.

    Para cada OmicSample com lista `sra_runs` não-vazia, cria uma SampleSraRun
    por run_accession. Idempotente: usa bulk_create(ignore_conflicts=True),
    que respeita o UniqueConstraint (sample, run_accession) — re-rodar não
    duplica. NÃO toca/remove o JSON original (limpeza é passo posterior, depois
    que ferris/vitruvio passarem a escrever/ler a tabela).
    """
    OmicSample = apps.get_model('core', 'OmicSample')
    SampleSraRun = apps.get_model('core', 'SampleSraRun')

    db_alias = schema_editor.connection.alias
    rows = []
    qs = (
        OmicSample.objects.using(db_alias)
        .filter(extra_metadata__has_key='sra_runs')
        .values_list('id', 'extra_metadata')
        .iterator(chunk_size=2000)
    )
    seen = set()  # (sample_id, run) — evita duplicata dentro do próprio JSON
    for sample_id, extra in qs:
        runs = (extra or {}).get('sra_runs') or []
        if not isinstance(runs, (list, tuple)):
            continue
        for run in runs:
            run = (run or '').strip()
            if not run:
                continue
            key = (sample_id, run)
            if key in seen:
                continue
            seen.add(key)
            rows.append(SampleSraRun(sample_id=sample_id, run_accession=run))
            if len(rows) >= 5000:
                SampleSraRun.objects.using(db_alias).bulk_create(
                    rows, ignore_conflicts=True
                )
                rows = []
    if rows:
        SampleSraRun.objects.using(db_alias).bulk_create(
            rows, ignore_conflicts=True
        )


def reverse_backfill_sra_runs(apps, schema_editor):
    """
    Reverso do backfill: esvazia SampleSraRun. Seguro porque a fonte de verdade
    (extra_metadata['sra_runs']) NÃO é removida no forward — o reverse apenas
    desfaz a materialização. Não é curadoria; nenhum campo de auditoria de
    ProjectSample é tocado.
    """
    SampleSraRun = apps.get_model('core', 'SampleSraRun')
    db_alias = schema_editor.connection.alias
    SampleSraRun.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_ingestionjob_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSraRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_accession', models.CharField(db_index=True, help_text='SRR*/ERR*/DRR* resolvido para o sample.', max_length=50, verbose_name='Run SRA')),
                ('fastq_url', models.TextField(blank=True, default='', help_text='URL pública do run na ENA (fastq_ftp). Pode conter mais de um arquivo separado por ";". Vazio até o cache ser populado.', verbose_name='URL(s) FASTQ (ENA)')),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Tamanho declarado pela ENA; soma da seleção alimenta a UX de quota.', null=True, verbose_name='Tamanho (bytes)')),
                ('checksum_md5', models.CharField(blank=True, help_text='MD5 declarado pela ENA por arquivo do run.', max_length=128, null=True, verbose_name='Checksum MD5 (ENA)')),
                ('resolved_at', models.DateTimeField(auto_now_add=True, verbose_name='Resolvido em')),
                ('sample', models.ForeignKey(help_text='O GSM dono da relação (OmicSample com accession GSM*).', on_delete=django.db.models.deletion.CASCADE, related_name='sra_runs', to='core.omicsample')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sample', 'run_accession'), name='samplesrarun_sample_run_uniq')],
            },
        ),
        migrations.RunPython(backfill_sra_runs, reverse_backfill_sra_runs),
    ]
