# Generated by Django 6.0.3 on 2026-06-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_samplesrarun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('pride_search', 'Busca PRIDE'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos'), ('geo_supplementary_download', 'Download Suplementar GEO'), ('fastq_download', 'Download FASTQ'), ('sra_resolution', 'Resolução GSM→SRR (GEO→SRA)'), ('matrix_load', 'Carga de Matriz (OmnisPathway Obj 2)')], max_length=30),
        ),
        migrations.CreateModel(
            name='OmicMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omics_layer', models.CharField(help_text='Camada ômica canônica (genomic, transcriptomic, proteomic, ...). Reusa OmicDataset.OMICS_LAYER_VOCAB.', max_length=40, verbose_name='Camada Ômica')),
                ('data_format_level', models.CharField(choices=[('counts', 'Counts (contagens brutas)'), ('tpm', 'TPM'), ('intensities', 'Intensidades (proteoma/MS)'), ('betas', 'Betas (metilação)')], help_text='Granularidade quantitativa da matriz (counts/TPM/intensities/betas).', max_length=20, verbose_name='Nível do Formato')),
                ('feature_axis', models.CharField(choices=[('gene', 'Gene'), ('protein', 'Proteína'), ('phospho_site', 'Fosfo-sítio'), ('probe', 'Probe')], help_text='Entidade indexada nas linhas da matriz.', max_length=20, verbose_name='Eixo de Features')),
                ('source_pointer', models.TextField(blank=True, default='', help_text='Cópia textual do matrix_pointer consumido (proveniência).', verbose_name='Ponteiro de Origem')),
                ('storage_key', models.TextField(blank=True, default='', help_text='Chave LÓGICA do artefato Parquet em default_storage. NUNCA caminho físico absoluto. Vazio até o upload concluir.', verbose_name='Storage Key')),
                ('n_features', models.PositiveIntegerField(blank=True, help_text='Linhas da matriz (features). NULL até a carga concluir.', null=True, verbose_name='Nº de Features')),
                ('n_samples', models.PositiveIntegerField(blank=True, help_text='Colunas da matriz (amostras). NULL até a carga concluir.', null=True, verbose_name='Nº de Amostras')),
                ('checksum_md5', models.CharField(blank=True, default='', help_text='MD5 do artefato Parquet (integridade).', max_length=128, verbose_name='Checksum MD5')),
                ('loader_version', models.CharField(help_text='Versão do loader Rust que produziu a matriz — parte da chave natural (re-carga com loader novo coexiste).', max_length=50, verbose_name='Versão do Loader')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Carregado em')),
                ('dataset', models.ForeignKey(help_text='Dataset ômico de origem da matriz.', on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='core.omicdataset')),
            ],
            options={
                'verbose_name': 'Omic matrix',
                'verbose_name_plural': 'Omic matrices',
            },
        ),
        migrations.CreateModel(
            name='OmicMatrixSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_index', models.PositiveIntegerField(help_text='Posição 0-based da coluna no artefato Parquet.', verbose_name='Índice da Coluna')),
                ('sample_role', models.CharField(choices=[('tumor', 'Tumor'), ('normal', 'Normal'), ('unknown', 'Desconhecido')], default='unknown', help_text='Papel no contraste pareado (tumor/normal/unknown).', max_length=10, verbose_name='Papel da Amostra')),
                ('matrix', models.ForeignKey(help_text='Matriz a que esta coluna pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='matrix_samples', to='core.omicmatrix')),
                ('sample', models.ForeignKey(help_text='Amostra canônica mapeada por esta coluna.', on_delete=django.db.models.deletion.CASCADE, related_name='matrix_columns', to='core.omicsample')),
            ],
        ),
        migrations.AddIndex(
            model_name='omicmatrix',
            index=models.Index(fields=['dataset', 'omics_layer'], name='omicmatrix_dataset_layer_idx'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.UniqueConstraint(fields=('dataset', 'omics_layer', 'feature_axis', 'loader_version'), name='omicmatrix_natural_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('omics_layer__in', ['genomic', 'transcriptomic', 'proteomic', 'metabolomic', 'epigenomic', 'metagenomic', 'microbiome'])), name='omicmatrix_omics_layer_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('data_format_level__in', ['counts', 'tpm', 'intensities', 'betas'])), name='omicmatrix_data_format_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('feature_axis__in', ['gene', 'protein', 'phospho_site', 'probe'])), name='omicmatrix_feature_axis_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrixsample',
            constraint=models.UniqueConstraint(fields=('matrix', 'sample'), name='omicmatrixsample_matrix_sample_uniq'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrixsample',
            constraint=models.UniqueConstraint(fields=('matrix', 'column_index'), name='omicmatrixsample_matrix_column_uniq'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrixsample',
            constraint=models.CheckConstraint(condition=models.Q(('sample_role__in', ['tumor', 'normal', 'unknown'])), name='omicmatrixsample_sample_role_valid'),
        ),
    ]
