# Generated by Django 6.0.3 on 2026-06-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_omic_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omicdataset',
            name='source_db',
            field=models.CharField(choices=[('geo', 'GEO (Gene Expression Omnibus)'), ('sra', 'Sequence Read Archive'), ('arrayexpress', 'ArrayExpress'), ('tcga', 'TCGA'), ('cptac', 'CPTAC (Clinical Proteomic Tumor Analysis Consortium)'), ('bioproject', 'BioProject'), ('gwas_catalog', 'GWAS Catalog')], max_length=20, verbose_name='Banco de Origem'),
        ),
    ]
