# Generated by Django 6.0.3 on 2026-06-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_omicdataset_source_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmicSamplePairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Paciente (case_id) que fundamenta o par. Denormalizado de OmicSample.characteristics["case_id"] para join/auditoria.', max_length=64, verbose_name='Case ID')),
                ('pairing_basis', models.CharField(choices=[('shared_case_id', 'Case_ID compartilhado'), ('sample_join_key', 'sample_join_key do export'), ('manual', 'Curadoria manual')], default='shared_case_id', help_text='Critério que fundamentou o par (shared_case_id nesta fase).', max_length=20, verbose_name='Base do Pareamento')),
                ('confidence', models.FloatField(default=1.0, help_text='Confiança do par (1.0 para shared_case_id validado contra sobreposição real na mesma matriz).', verbose_name='Confiança')),
                ('validated_overlap', models.BooleanField(default=False, help_text='True quando tumor E normal existem para o case_id na MESMA matriz (sobreposição real confirmada, não assumida).', verbose_name='Sobreposição Validada')),
                ('pairing_version', models.CharField(blank=True, default='', help_text='Versão do algoritmo de pareamento que produziu o par.', max_length=50, verbose_name='Versão do Pareamento')),
                ('paired_at', models.DateTimeField(auto_now_add=True, verbose_name='Pareado em')),
                ('matrix', models.ForeignKey(help_text='Matriz (estudo+camada+versão do loader) que ancora o par.', on_delete=django.db.models.deletion.CASCADE, related_name='sample_pairings', to='core.omicmatrix')),
                ('normal_sample', models.ForeignKey(help_text='Amostra com papel normal do par.', on_delete=django.db.models.deletion.CASCADE, related_name='as_normal_in_pairings', to='core.omicsample')),
                ('tumor_sample', models.ForeignKey(help_text='Amostra com papel tumor do par.', on_delete=django.db.models.deletion.CASCADE, related_name='as_tumor_in_pairings', to='core.omicsample')),
            ],
            options={
                'verbose_name': 'Omic sample pairing',
                'verbose_name_plural': 'Omic sample pairings',
                'indexes': [models.Index(fields=['case_id'], name='omicsamplepairing_case_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('matrix', 'case_id'), name='omicsamplepairing_natural_key_uniq'), models.CheckConstraint(condition=models.Q(('pairing_basis__in', ['shared_case_id', 'sample_join_key', 'manual'])), name='omicsamplepairing_pairing_basis_valid')],
            },
        ),
    ]
