# Generated by Django 6.0.3 on 2026-07-11 11:59
#
# OmnisPathway Objetivo 2, Fase 2 — anotação de efeito de variante.
# Quatro modelos: GeneRole (2A), VariantEffectRaw (2B), VariantEffectResolved
# (2C) — catálogo global de referência, sem FK de projeto — e VariantEffectSeed
# (2D/2E) — seed por amostra derivada da matriz (isolamento via ProjectDataset).
# Design travado (objetivo2.md §1): magnitude por precedência
# ClinVar>AlphaMissense>dbNSFP; direção por magnitude + papel do gene; CNV
# não-monotônico (estado conjunto CNV×alelo). Migration reversível (só
# CreateModel — reverse dropa as tabelas). Nada de FK de projeto.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_omicsamplepairing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, help_text='UPPERCASE normalizado — casa por igualdade exata com VariantEffectRaw.gene_symbol / DatasetGene.gene_symbol.', max_length=50, verbose_name='Símbolo do Gene')),
                ('entrez_id', models.BigIntegerField(blank=True, help_text='Xref estável quando disponível.', null=True, verbose_name='Entrez Gene ID')),
                ('role', models.CharField(choices=[('oncogene', 'Oncogene'), ('tsg', 'Tumor Suppressor Gene'), ('oncogene_and_tsg', 'Oncogene e TSG (papel duplo)'), ('neither', 'Nenhum (listado, sem papel definido)'), ('unknown', 'Desconhecido')], db_index=True, default='unknown', help_text='oncogene/tsg/oncogene_and_tsg/neither/unknown — resolve a DIREÇÃO do sinal (com a magnitude).', max_length=20, verbose_name='Papel do Gene')),
                ('cgc_flag', models.BooleanField(default=False, help_text='Cross-check: gene está no COSMIC Cancer Gene Census (bundled no cancerGeneList.txt do OncoKB). Preservado sem colapsar divergência com role (resolução é do vitruvio).', verbose_name='Flag CGC')),
                ('vogelstein_flag', models.BooleanField(default=False, help_text='Cross-check: gene está na lista Vogelstein (bundled no cancerGeneList.txt do OncoKB).', verbose_name='Flag Vogelstein')),
                ('source', models.CharField(choices=[('oncokb', 'OncoKB'), ('cgc', 'COSMIC Cancer Gene Census')], db_index=True, help_text='Fonte autoritativa do papel (oncokb primária; cgc quando carregado direto do Census).', max_length=20, verbose_name='Fonte')),
                ('source_version', models.CharField(blank=True, default='', help_text='Release da fonte (ex.: OncoKB data version).', max_length=100, verbose_name='Versão/Release da Fonte')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Carregado em')),
            ],
            options={
                'verbose_name': 'Gene role',
                'verbose_name_plural': 'Gene roles',
                'constraints': [models.UniqueConstraint(fields=('gene_symbol', 'source'), name='generole_gene_source_uniq'), models.CheckConstraint(condition=models.Q(('role__in', ['oncogene', 'tsg', 'oncogene_and_tsg', 'neither', 'unknown'])), name='generole_role_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['oncokb', 'cgc'])), name='generole_source_valid')],
            },
        ),
        migrations.CreateModel(
            name='VariantEffectRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_key', models.CharField(db_index=True, help_text='CHROM:POS:REF:ALT normalizado em GRCh38 (chave canônica; NÃO rs-number). Idêntico entre fontes p/ a mesma variante.', max_length=128, verbose_name='Chave da Variante')),
                ('gene_symbol', models.CharField(db_index=True, help_text='UPPERCASE. Uma variante pode anotar >1 gene (por isso entra na natural key).', max_length=50, verbose_name='Símbolo do Gene')),
                ('source', models.CharField(choices=[('clinvar', 'ClinVar'), ('alphamissense', 'AlphaMissense'), ('dbnsfp', 'dbNSFP')], db_index=True, help_text='clinvar/alphamissense/dbnsfp — a ordem de precedência da combinação (2C) é ClinVar > AlphaMissense > dbNSFP.', max_length=20, verbose_name='Fonte')),
                ('raw_magnitude', models.FloatField(blank=True, help_text='Score numérico cru da fonte (AlphaMissense pathogenicity [0,1]; dbNSFP consenso). ClinVar não tem score → NULL (usar raw_class).', null=True, verbose_name='Magnitude Crua')),
                ('raw_class', models.CharField(blank=True, default='', help_text='Classe categórica crua (ClinVar Pathogenic/Benign; AlphaMissense likely_pathogenic/ambiguous/likely_benign; dbNSFP consenso textual).', max_length=128, verbose_name='Classe Crua')),
                ('clinvar_significance', models.CharField(blank=True, default='', help_text='Texto cru de clinical significance do ClinVar germinativo (preservado para auditoria; só relevante quando source=clinvar).', max_length=255, verbose_name='Significância Clínica (ClinVar)')),
                ('oncogenicity', models.CharField(blank=True, default='', help_text='Classificação de oncogenicidade do ClinVar somático (Oncogenic/Likely Oncogenic/VUS/... quando disponível); complementa clinvar_significance para variante somática.', max_length=64, verbose_name='Oncogenicidade (ClinVar somático)')),
                ('am_pathogenicity', models.FloatField(blank=True, help_text='Score [0,1] do AlphaMissense preservado explícito (além de raw_magnitude) para auditoria da precedência.', null=True, verbose_name='AlphaMissense Pathogenicity')),
                ('confidence', models.FloatField(blank=True, help_text='Confiança crua da fonte quando disponível (ex.: nº de submissões ClinVar, star rating); NULL se a fonte não fornece.', null=True, verbose_name='Confiança da Anotação')),
                ('source_version', models.CharField(blank=True, default='', help_text='Release da fonte + build de referência (proveniência da normalização GRCh37→GRCh38).', max_length=100, verbose_name='Versão/Release da Fonte')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Carregado em')),
            ],
            options={
                'verbose_name': 'Variant effect (raw)',
                'verbose_name_plural': 'Variant effects (raw)',
                'indexes': [models.Index(fields=['variant_key', 'gene_symbol'], name='vefraw_vkey_gene_idx'), models.Index(fields=['gene_symbol', 'source'], name='vefraw_gene_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('variant_key', 'source', 'gene_symbol'), name='varianteffectraw_natural_key_uniq'), models.CheckConstraint(condition=models.Q(('source__in', ['clinvar', 'alphamissense', 'dbnsfp'])), name='varianteffectraw_source_valid')],
            },
        ),
        migrations.CreateModel(
            name='VariantEffectResolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_key', models.CharField(db_index=True, help_text='CHROM:POS:REF:ALT em GRCh38 (mesma convenção de VariantEffectRaw).', max_length=128, verbose_name='Chave da Variante')),
                ('gene_symbol', models.CharField(db_index=True, help_text='UPPERCASE.', max_length=50, verbose_name='Símbolo do Gene')),
                ('magnitude', models.FloatField(help_text='Magnitude de dano normalizada em [0,1] (Decisão E-K: escala comum entre fontes; categórico ClinVar mapeado p/ âncoras).', verbose_name='Magnitude Resolvida')),
                ('effect_class', models.CharField(blank=True, default='', help_text='Classe funcional resolvida (ex.: missense, nonsense/LoF) que fundamentou magnitude/direção — auditoria da resolução.', max_length=64, verbose_name='Classe do Efeito')),
                ('direction', models.CharField(choices=[('activator', 'Ativador (GoF)'), ('inactivator', 'Inativador (LoF)'), ('neutral', 'Neutro')], db_index=True, default='neutral', help_text='activator (GoF) / inactivator (LoF) / neutral — magnitude + papel do gene.', max_length=20, verbose_name='Direção do Efeito')),
                ('confidence', models.FloatField(default=0.0, help_text='Confiança [0,1] herdada da fonte vencedora + concordância dos preditores.', verbose_name='Confiança da Resolução')),
                ('effect_source', models.CharField(choices=[('clinvar', 'ClinVar'), ('alphamissense', 'AlphaMissense'), ('dbnsfp', 'dbNSFP')], db_index=True, help_text='Qual fonte venceu a precedência da magnitude (clinvar/alphamissense/dbnsfp).', max_length=20, verbose_name='Fonte Vencedora (magnitude)')),
                ('gene_role_used', models.CharField(choices=[('oncogene', 'Oncogene'), ('tsg', 'Tumor Suppressor Gene'), ('oncogene_and_tsg', 'Oncogene e TSG (papel duplo)'), ('neither', 'Nenhum (listado, sem papel definido)'), ('unknown', 'Desconhecido')], default='unknown', help_text='Papel (denorm de GeneRole) que resolveu a direção — oncogene/tsg/oncogene_and_tsg/neither/unknown.', max_length=20, verbose_name='Papel do Gene Usado')),
                ('resolution_version', models.CharField(help_text='Versão do algoritmo de combinação (ex.: fase2-v1) — parte da chave natural; reprocessar coexiste com versão anterior.', max_length=50, verbose_name='Versão da Resolução')),
                ('resolved_at', models.DateTimeField(auto_now=True, verbose_name='Resolvido em')),
            ],
            options={
                'verbose_name': 'Variant effect (resolved)',
                'verbose_name_plural': 'Variant effects (resolved)',
                'indexes': [models.Index(fields=['variant_key', 'gene_symbol'], name='vefresolved_vkey_gene_idx'), models.Index(fields=['gene_symbol', 'resolution_version'], name='vefresolved_gene_version_idx')],
                'constraints': [models.UniqueConstraint(fields=('variant_key', 'gene_symbol', 'resolution_version'), name='varianteffectresolved_natural_key_uniq'), models.CheckConstraint(condition=models.Q(('direction__in', ['activator', 'inactivator', 'neutral'])), name='varianteffectresolved_direction_valid'), models.CheckConstraint(condition=models.Q(('effect_source__in', ['clinvar', 'alphamissense', 'dbnsfp'])), name='varianteffectresolved_effect_source_valid'), models.CheckConstraint(condition=models.Q(('gene_role_used__in', ['oncogene', 'tsg', 'oncogene_and_tsg', 'neither', 'unknown'])), name='varianteffectresolved_gene_role_used_valid')],
            },
        ),
        migrations.CreateModel(
            name='VariantEffectSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, help_text='UPPERCASE. CNV é nível-gene; SNV também carrega o gene.', max_length=50, verbose_name='Símbolo do Gene')),
                ('variant_key', models.CharField(blank=True, db_index=True, default='', help_text='CHROM:POS:REF:ALT (GRCh38) para SNV. VAZIO para CNV (nível-gene, sem posição). NULL-like via string vazia p/ compor a natural key sem coluna nullable.', max_length=128, verbose_name='Chave da Variante')),
                ('evidence_type', models.CharField(choices=[('snv', 'SNV (single-nucleotide variant)'), ('cnv', 'CNV (copy-number variation)')], db_index=True, help_text='snv (precedência) / cnv (estado conjunto não-monotônico).', max_length=10, verbose_name='Tipo de Evidência')),
                ('direction', models.CharField(choices=[('activator', 'Ativador (GoF)'), ('inactivator', 'Inativador (LoF)'), ('neutral', 'Neutro')], db_index=True, default='neutral', help_text='activator/inactivator/neutral — sinal já resolvido que o PFS propaga (nunca o evento cru).', max_length=20, verbose_name='Direção do Efeito')),
                ('magnitude', models.FloatField(help_text='Magnitude do efeito normalizada [0,1] (herda de VariantEffectResolved para SNV; resolução CNV×alelo p/ CNV).', verbose_name='Magnitude')),
                ('confidence', models.FloatField(default=0.0, help_text='Confiança [0,1] da seed.', verbose_name='Confiança')),
                ('gene_role', models.CharField(choices=[('oncogene', 'Oncogene'), ('tsg', 'Tumor Suppressor Gene'), ('oncogene_and_tsg', 'Oncogene e TSG (papel duplo)'), ('neither', 'Nenhum (listado, sem papel definido)'), ('unknown', 'Desconhecido')], default='unknown', help_text='Papel denormalizado (de GeneRole) que fundamentou a direção — evita re-join na leitura do PFS.', max_length=20, verbose_name='Papel do Gene (denorm)')),
                ('effect_source', models.CharField(blank=True, default='', help_text='Fonte que resolveu (denorm de VariantEffectResolved.effect_source + gene_role_used para SNV; base do CNV p/ CNV).', max_length=64, verbose_name='Fonte do Efeito')),
                ('method_version', models.CharField(help_text='Versão do método de seeding (ex.: fase2-v1) — parte da proveniência; re-seed coexiste/UPSERT.', max_length=50, verbose_name='Versão do Método')),
                ('resolved_at', models.DateTimeField(auto_now_add=True, verbose_name='Resolvido em')),
                ('matrix', models.ForeignKey(help_text='Matriz (estudo+camada+versão do loader) que ancora a seed.', on_delete=django.db.models.deletion.CASCADE, related_name='effect_seeds', to='core.omicmatrix')),
                ('sample', models.ForeignKey(help_text='Amostra onde o evento ocorre (ocorrência, não catálogo).', on_delete=django.db.models.deletion.CASCADE, related_name='effect_seeds', to='core.omicsample')),
            ],
            options={
                'verbose_name': 'Variant effect seed',
                'verbose_name_plural': 'Variant effect seeds',
                'indexes': [models.Index(fields=['matrix', 'sample'], name='vefseed_matrix_sample_idx'), models.Index(fields=['gene_symbol'], name='vefseed_gene_idx')],
                'constraints': [models.UniqueConstraint(fields=('matrix', 'sample', 'gene_symbol', 'variant_key', 'evidence_type'), name='varianteffectseed_natural_key_uniq'), models.CheckConstraint(condition=models.Q(('evidence_type__in', ['snv', 'cnv'])), name='varianteffectseed_evidence_type_valid'), models.CheckConstraint(condition=models.Q(('direction__in', ['activator', 'inactivator', 'neutral'])), name='varianteffectseed_direction_valid'), models.CheckConstraint(condition=models.Q(('gene_role__in', ['oncogene', 'tsg', 'oncogene_and_tsg', 'neither', 'unknown'])), name='varianteffectseed_gene_role_valid')],
            },
        ),
    ]
