# Generated by Django 6.0.3 on 2026-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_variant_effect'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='omicdataset',
            name='omicdataset_omics_layers_valid',
        ),
        migrations.RemoveConstraint(
            model_name='omicmatrix',
            name='omicmatrix_omics_layer_valid',
        ),
        migrations.RemoveConstraint(
            model_name='omicmatrix',
            name='omicmatrix_data_format_level_valid',
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('pride_search', 'Busca PRIDE'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos'), ('geo_supplementary_download', 'Download Suplementar GEO'), ('fastq_download', 'Download FASTQ'), ('sra_resolution', 'Resolução GSM→SRR (GEO→SRA)'), ('matrix_load', 'Carga de Matriz (OmnisPathway Obj 2)'), ('gene_role_load', 'Carga de Papéis de Gene (OncoKB, Obj 2)'), ('cnv_matrix_load', 'Carga de Matriz CNV (OmnisPathway Obj 2)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='omicmatrix',
            name='data_format_level',
            field=models.CharField(choices=[('counts', 'Counts (contagens brutas)'), ('tpm', 'TPM'), ('intensities', 'Intensidades (proteoma/MS)'), ('betas', 'Betas (metilação)'), ('log_ratio', 'Log-ratio (CNV contínuo)')], help_text='Granularidade quantitativa da matriz (counts/TPM/intensities/betas/log_ratio).', max_length=20, verbose_name='Nível do Formato'),
        ),
        migrations.AlterField(
            model_name='omicmatrix',
            name='omics_layer',
            field=models.CharField(help_text='Camada ômica canônica (genomic, transcriptomic, proteomic, copy_number, ...). Reusa OmicDataset.OMICS_LAYER_VOCAB.', max_length=40, verbose_name='Camada Ômica'),
        ),
        migrations.AddConstraint(
            model_name='omicdataset',
            constraint=models.CheckConstraint(condition=models.Q(('omics_layers__contained_by', ['genomic', 'transcriptomic', 'proteomic', 'metabolomic', 'epigenomic', 'metagenomic', 'microbiome', 'copy_number'])), name='omicdataset_omics_layers_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('omics_layer__in', ['genomic', 'transcriptomic', 'proteomic', 'metabolomic', 'epigenomic', 'metagenomic', 'microbiome', 'copy_number'])), name='omicmatrix_omics_layer_valid'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('data_format_level__in', ['counts', 'tpm', 'intensities', 'betas', 'log_ratio'])), name='omicmatrix_data_format_level_valid'),
        ),
    ]
