# Generated by Django 6.0.3 on 2026-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_omicdataset_omicdataset_omics_layers_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('pride_search', 'Busca PRIDE'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos'), ('geo_supplementary_download', 'Download Suplementar GEO'), ('fastq_download', 'Download FASTQ'), ('sra_resolution', 'Resolução GSM→SRR (GEO→SRA)'), ('matrix_load', 'Carga de Matriz (OmnisPathway Obj 2)'), ('gene_role_load', 'Carga de Papéis de Gene (OncoKB, Obj 2)'), ('cnv_matrix_load', 'Carga de Matriz CNV (OmnisPathway Obj 2)'), ('cnv_seed_load', 'Derivação de Seed CNV (OmnisPathway Obj 2)')], max_length=30),
        ),
    ]
