# Generated by Django 6.0.3 on 2026-07-13 18:42
#
# OmnisPathway Objetivo 2, Fase 2 — incremento CNV×alelo (2.7).
# WIDENING da chave natural de VariantEffectSeed: adiciona `method_version` à
# UniqueConstraint, de (matrix, sample, gene_symbol, variant_key, evidence_type)
# para (…, method_version). Objetivo: versões de método (fase2-cnv-v2,
# fase2-cnv-v1, fase2-snv-v1) COEXISTIREM sem sobrescrever — habilita benchmark.
#
# ADITIVA e segura: alargar a tupla única só admite MAIS linhas, nunca viola
# linhas existentes (as seeds atuais têm method_version distinta por
# evidence_type, sem colisão). Reversível: o reverse remove a constraint larga e
# recria a estreita anterior. CAUTELA na reversão — se algum dia existirem 2
# linhas que difiram APENAS em method_version, o reverse falharia (constraint
# estreita violada); hoje isso não ocorre. Nenhuma coluna dropada; auditoria
# preservada. Não toca o COPY writer (colunas inalteradas).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_ingestionjob_job_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='varianteffectseed',
            name='varianteffectseed_natural_key_uniq',
        ),
        migrations.AlterField(
            model_name='varianteffectseed',
            name='method_version',
            field=models.CharField(help_text='Versão do método de seeding (ex.: fase2-cnv-v2, fase2-cnv-v1, fase2-snv-v1) — PARTE DA CHAVE NATURAL: versões coexistem sem sobrescrever (benchmark entre métodos); re-seed da mesma versão é idempotente/UPSERT.', max_length=50, verbose_name='Versão do Método'),
        ),
        migrations.AddConstraint(
            model_name='varianteffectseed',
            constraint=models.UniqueConstraint(fields=('matrix', 'sample', 'gene_symbol', 'variant_key', 'evidence_type', 'method_version'), name='varianteffectseed_natural_key_uniq'),
        ),
    ]
