# Generated by Django 6.0.3 on 2026-07-16 12:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_variant_effect_seed_method_version_natural_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('pride_search', 'Busca PRIDE'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos'), ('geo_supplementary_download', 'Download Suplementar GEO'), ('fastq_download', 'Download FASTQ'), ('sra_resolution', 'Resolução GSM→SRR (GEO→SRA)'), ('matrix_load', 'Carga de Matriz (OmnisPathway Obj 2)'), ('gene_role_load', 'Carga de Papéis de Gene (OncoKB, Obj 2)'), ('cnv_matrix_load', 'Carga de Matriz CNV (OmnisPathway Obj 2)'), ('cnv_seed_load', 'Derivação de Seed CNV (OmnisPathway Obj 2)'), ('variant_effect_raw_load', 'Carga de Efeito Cru de Variante (ClinVar/AlphaMissense) (OmnisPathway Obj 2)'), ('somatic_maf_load', 'Carga de MAF Somático GDC (OmnisPathway Obj 2)'), ('snv_seed_load', 'Derivação de Seed SNV (OmnisPathway Obj 2)'), ('pathway_topology_load', 'Carga de Topologia KEGG (OmnisPathway Obj 2)'), ('regulon_load', 'Carga de Regulons CollecTRI/OmniPath (OmnisPathway Obj 2)'), ('phospho_matrix_load', 'Carga de Matriz de Fosfoproteoma (OmnisPathway Obj 2)'), ('readout_mapping', 'Mapeamento Readout→Feature (OmnisPathway Obj 2)')], max_length=30),
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegg_id', models.CharField(help_text='ex.: hsa04151/hsa04010/hsa04115 — NATURAL KEY.', max_length=20, verbose_name='ID KEGG da Via')),
                ('name', models.CharField(blank=True, default='', help_text='Nome KEGG (ex.: "PI3K-Akt signaling pathway").', max_length=255, verbose_name='Nome da Via')),
                ('source', models.CharField(choices=[('kegg', 'KEGG')], default='kegg', help_text='kegg (v1) — reservado p/ Reactome/WikiPathways futuros.', max_length=20, verbose_name='Fonte')),
                ('source_version', models.CharField(blank=True, default='', help_text='Release KEGG (data do download) — proveniência/reprodutibilidade.', max_length=100, verbose_name='Versão/Release da Fonte')),
                ('n_nodes', models.PositiveIntegerField(blank=True, help_text='Preenchido ao concluir a carga do grafo.', null=True, verbose_name='Nº de Nós')),
                ('n_edges', models.PositiveIntegerField(blank=True, help_text='Preenchido ao concluir a carga do grafo.', null=True, verbose_name='Nº de Arestas')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Carregado em')),
            ],
            options={
                'verbose_name': 'Pathway',
                'verbose_name_plural': 'Pathways',
                'constraints': [models.UniqueConstraint(fields=('kegg_id',), name='pathway_kegg_id_uniq'), models.CheckConstraint(condition=models.Q(('source__in', ['kegg'])), name='pathway_source_valid')],
            },
        ),
        migrations.CreateModel(
            name='PathwayNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegg_entry_id', models.CharField(help_text='ID do <entry id="…"> no KGML (único no escopo da via).', max_length=32, verbose_name='ID do Entry KGML')),
                ('node_type', models.CharField(choices=[('gene', 'Gene'), ('compound', 'Composto'), ('group', 'Grupo (complexo)'), ('map', 'Mapa (via ligada)'), ('ortholog', 'Ortólogo')], help_text='Do atributo <entry type> (gene/compound/group/map/ortholog).', max_length=20, verbose_name='Tipo do Nó')),
                ('kegg_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='IDs KEGG crus do entry (hsa:5290 etc.; pode agrupar genes).')),
                ('gene_symbol', models.CharField(blank=True, default='', help_text='Símbolo UPPERCASE do graphics name (Decisão 6). Vazio p/ compound/map. Chave de junção com features da matriz.', max_length=50, verbose_name='Símbolo do Gene')),
                ('graphics_name', models.CharField(blank=True, default='', help_text='graphics name cru do KGML — proveniência do símbolo.', max_length=255, verbose_name='Graphics Name (cru)')),
                ('readout_role', models.CharField(choices=[('none', 'Nenhum'), ('phospho', 'Fosforilação (Regra 1)'), ('tf_target', 'Alvo de TF (Regra 2)'), ('metabolite', 'Metabólito (Regra 3, reservado)')], default='none', help_text='none/phospho/tf_target/metabolite — marcado no mapeamento readout (Regra 1/2/3).', max_length=20, verbose_name='Papel de Readout')),
                ('is_seed_target', models.BooleanField(default=False, help_text='Reservado p/ Fase 4 (nó que recebe semente genômica).', verbose_name='É Alvo de Semente')),
                ('pathway', models.ForeignKey(help_text='Via a que este nó pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.pathway')),
            ],
            options={
                'verbose_name': 'Pathway node',
                'verbose_name_plural': 'Pathway nodes',
            },
        ),
        migrations.CreateModel(
            name='PathwayEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.SmallIntegerField(help_text='+1 (ativante) / −1 (inibitório) / 0 (associação/sem sinal) — derivado do subtype.name (§Sinal). Coração do grafo assinado; consumido pelo RWR da Fase 4.', verbose_name='Sinal')),
                ('relation_type', models.CharField(choices=[('ecrel', 'Enzyme-enzyme relation'), ('pprel', 'Protein-protein relation'), ('gerel', 'Gene expression relation'), ('pcrel', 'Protein-compound relation'), ('maplink', 'Link to another map')], help_text='Do <relation type> (ecrel/pprel/gerel/pcrel/maplink).', max_length=20, verbose_name='Tipo da Relation')),
                ('subtypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='subtype.name crus (activation/inhibition/phosphorylation/…) — proveniência do sinal.')),
                ('interaction', models.CharField(choices=[('activation', 'Ativação'), ('inhibition', 'Inibição'), ('expression', 'Expressão'), ('repression', 'Repressão'), ('binding', 'Ligação/associação'), ('indirect', 'Efeito indireto'), ('unknown', 'Desconhecido')], help_text='Rótulo derivado do subtype (§Sinal). PARTE DA NATURAL KEY (evita colisão de arestas multi-relation no mesmo par).', max_length=20, verbose_name='Interação (derivada)')),
                ('pathway', models.ForeignKey(help_text='Via a que esta aresta pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.pathway')),
                ('source_node', models.ForeignKey(help_text='entry1 do <relation> — origem da aresta direcionada.', on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='core.pathwaynode')),
                ('target_node', models.ForeignKey(help_text='entry2 do <relation> — destino da aresta direcionada.', on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='core.pathwaynode')),
            ],
            options={
                'verbose_name': 'Pathway edge',
                'verbose_name_plural': 'Pathway edges',
            },
        ),
        migrations.CreateModel(
            name='PathwayReadoutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text='Feature na matriz: símbolo de gene (TP53) ou fosfo-sítio (TP53_S15).', max_length=128, verbose_name='Chave da Feature')),
                ('rule', models.CharField(choices=[('phospho', 'Fosforilação (Regra 1)'), ('tf_target', 'Alvo de TF (Regra 2)'), ('metabolite', 'Metabólito (Regra 3, reservado)')], help_text='phospho (Regra 1) / tf_target (Regra 2) / metabolite (Regra 3, reservado).', max_length=20, verbose_name='Regra de Mapeamento')),
                ('regulon_source', models.CharField(blank=True, default='', help_text='p/ Regra 2: collectri (via OmniPath); vazio p/ Regra 1.', max_length=20, verbose_name='Fonte do Regulon')),
                ('regulon_sign', models.SmallIntegerField(blank=True, help_text='p/ Regra 2: modo de regulação TF→alvo (+1/−1) do CollecTRI; NULL p/ Regra 1.', null=True, verbose_name='Sinal do Regulon')),
                ('confidence', models.FloatField(default=0.0, help_text='Confiança do mapeamento (DoRothEA A-E → escala; Regra 1 = 1.0 se o sítio bate).', verbose_name='Confiança')),
                ('mapping_version', models.CharField(help_text='ex.: fase3-readout-v1 — PARTE DA NATURAL KEY (versões coexistem sem sobrescrever).', max_length=50, verbose_name='Versão do Mapeamento')),
                ('matrix', models.ForeignKey(help_text='Matriz onde a feature vive (fosfoproteoma p/ Regra 1; expressão/proteoma p/ Regra 2).', on_delete=django.db.models.deletion.CASCADE, related_name='readout_features', to='core.omicmatrix')),
                ('node', models.ForeignKey(help_text='Nó de readout do grafo mapeado a esta feature.', on_delete=django.db.models.deletion.CASCADE, related_name='readout_features', to='core.pathwaynode')),
            ],
            options={
                'verbose_name': 'Pathway readout feature',
                'verbose_name_plural': 'Pathway readout features',
            },
        ),
        migrations.AddIndex(
            model_name='pathwaynode',
            index=models.Index(fields=['pathway', 'gene_symbol'], name='pnode_pathway_symbol_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwaynode',
            index=models.Index(fields=['pathway', 'readout_role'], name='pnode_pathway_readout_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathwaynode',
            constraint=models.UniqueConstraint(fields=('pathway', 'kegg_entry_id'), name='pathwaynode_pathway_entry_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pathwaynode',
            constraint=models.CheckConstraint(condition=models.Q(('node_type__in', ['gene', 'compound', 'group', 'map', 'ortholog'])), name='pathwaynode_node_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='pathwaynode',
            constraint=models.CheckConstraint(condition=models.Q(('readout_role__in', ['none', 'phospho', 'tf_target', 'metabolite'])), name='pathwaynode_readout_role_valid'),
        ),
        migrations.AddIndex(
            model_name='pathwayedge',
            index=models.Index(fields=['pathway', 'source_node'], name='pathwayedge_pathway_source_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwayedge',
            index=models.Index(fields=['pathway', 'target_node'], name='pathwayedge_pathway_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathwayedge',
            constraint=models.UniqueConstraint(fields=('pathway', 'source_node', 'target_node', 'interaction'), name='pathwayedge_natural_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pathwayedge',
            constraint=models.CheckConstraint(condition=models.Q(('relation_type__in', ['ecrel', 'pprel', 'gerel', 'pcrel', 'maplink'])), name='pathwayedge_relation_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='pathwayedge',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__in', ['activation', 'inhibition', 'expression', 'repression', 'binding', 'indirect', 'unknown'])), name='pathwayedge_interaction_valid'),
        ),
        migrations.AddIndex(
            model_name='pathwayreadoutfeature',
            index=models.Index(fields=['matrix', 'feature_key'], name='pathwayrf_matrix_feature_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathwayreadoutfeature',
            constraint=models.UniqueConstraint(fields=('node', 'matrix', 'feature_key', 'rule', 'mapping_version'), name='pathwayreadoutfeature_natural_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pathwayreadoutfeature',
            constraint=models.CheckConstraint(condition=models.Q(('rule__in', ['phospho', 'tf_target', 'metabolite'])), name='pathwayreadoutfeature_rule_valid'),
        ),
    ]
