# Generated by Django 6.0.3 on 2026-07-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_pathway_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmicMatrixFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text='Feature como aparece na matriz, UPPERCASE: símbolo de gene (TP53) ou fosfo-sítio (TP53_S15). Mesmo vocabulário de PathwayReadoutFeature.feature_key.', max_length=128, verbose_name='Chave da Feature')),
                ('row_index', models.PositiveIntegerField(help_text='Posição 0-based da linha no artefato Parquet.', verbose_name='Índice da Linha')),
                ('matrix', models.ForeignKey(help_text='Matriz a que esta linha pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.omicmatrix')),
            ],
            options={
                'verbose_name': 'Omic matrix feature',
                'verbose_name_plural': 'Omic matrix features',
                'constraints': [models.UniqueConstraint(fields=('matrix', 'feature_key'), name='omicmatrixfeature_matrix_feature_uniq'), models.UniqueConstraint(fields=('matrix', 'row_index'), name='omicmatrixfeature_matrix_row_uniq')],
            },
        ),
    ]
