# Generated by Django 6.0.3 on 2026-07-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_omicmatrixfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='job_type',
            field=models.CharField(choices=[('pubmed_search', 'Busca PubMed'), ('pubmed_fetch', 'Fetch PubMed XML'), ('geo_search', 'Busca GEO'), ('sra_search', 'Busca SRA'), ('gwas_search', 'Busca GWAS Catalog'), ('pride_search', 'Busca PRIDE'), ('sample_fetch', 'Fetch de Amostras'), ('variant_annotation', 'Anotação de Variantes'), ('gene_ner', 'Extração de Genes'), ('drug_ner', 'Extração de Drogas'), ('context_extraction', 'Extração de Contextos'), ('geo_supplementary_download', 'Download Suplementar GEO'), ('fastq_download', 'Download FASTQ'), ('sra_resolution', 'Resolução GSM→SRR (GEO→SRA)'), ('matrix_load', 'Carga de Matriz (OmnisPathway Obj 2)'), ('gene_role_load', 'Carga de Papéis de Gene (OncoKB, Obj 2)'), ('cnv_matrix_load', 'Carga de Matriz CNV (OmnisPathway Obj 2)'), ('cnv_seed_load', 'Derivação de Seed CNV (OmnisPathway Obj 2)'), ('variant_effect_raw_load', 'Carga de Efeito Cru de Variante (ClinVar/AlphaMissense) (OmnisPathway Obj 2)'), ('somatic_maf_load', 'Carga de MAF Somático GDC (OmnisPathway Obj 2)'), ('snv_seed_load', 'Derivação de Seed SNV (OmnisPathway Obj 2)'), ('pathway_topology_load', 'Carga de Topologia KEGG (OmnisPathway Obj 2)'), ('regulon_load', 'Carga de Regulons CollecTRI/OmniPath (OmnisPathway Obj 2)'), ('phospho_matrix_load', 'Carga de Matriz de Fosfoproteoma (OmnisPathway Obj 2)'), ('readout_mapping', 'Mapeamento Readout→Feature (OmnisPathway Obj 2)'), ('pathway_score_run', 'Execução do Motor PFS (OmnisPathway Obj 2, Fase 4)')], max_length=30),
        ),
        migrations.CreateModel(
            name='PathwayActivityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Estatística observada da leitura por Regras: média(p_v · Δx_v | Regra 1) + média(p_t · a_t | Regra 2). Média (não soma) por regra → vias com nº de readouts diferente ficam comparáveis.', verbose_name='Escore Observado (S_obs)')),
                ('null_mean', models.FloatField(help_text='Média da distribuição nula (permutação da POSIÇÃO das sementes, estratificada por quartil de out-degree).', verbose_name='Média da Nula')),
                ('null_sd', models.FloatField(help_text='Desvio-padrão da nula. 0.0 → z_score = 0 por convenção (D7); é sintoma de cobertura, não de bug.', verbose_name='Desvio-padrão da Nula')),
                ('z_score', models.FloatField(help_text='(S_obs − null_mean)/null_sd. É o PFS CONTÍNUO primário — comparável entre vias e amostras.', verbose_name='Z-score (PFS primário)')),
                ('p_empirical', models.FloatField(help_text='Bicaudal com correção +1: (1 + #{|S_null| ≥ |S_obs|})/(1+B). Satura em 1/(B+1) → anotação de significância, NÃO ranking.', verbose_name='p Empírico')),
                ('n_permutations', models.PositiveIntegerField(default=0, help_text='B efetivo usado na nula (default 1000).', verbose_name='Nº de Permutações (B)')),
                ('n_seeds_on_graph', models.PositiveIntegerField(default=0, help_text='Sementes desta amostra que caíram em nó gene/ortholog DESTA via (peso dividido w/k entre nós homônimos).', verbose_name='Sementes no Grafo')),
                ('n_seeds_off_graph', models.PositiveIntegerField(default=0, help_text='Sementes descartadas por não haver nó com o símbolo nesta via — esperado e correto (a via é o recorte), mas CONTADO: on/off é a cobertura de semente por via e amostra (D-5).', verbose_name='Sementes Fora do Grafo')),
                ('n_readouts_mapped', models.PositiveIntegerField(default=0, help_text='Linhas de PathwayReadoutFeature desta via/mapping_version (ambas as regras). NÃO é o denominador do escore — inclui readouts fantasma (36% na Regra 1 na medição live).', verbose_name='Readouts Mapeados (candidatos)')),
                ('n_readouts_with_value', models.PositiveIntegerField(default=0, help_text='Readouts com feature real E valor no Parquet neste par — É ESTE o denominador da normalização. Nunca imputar zero para ausência: zero é um valor, ausência não é.', verbose_name='Readouts com Valor Real')),
                ('n_readouts_missing', models.PositiveIntegerField(default=0, help_text='mapped − with_value: mapeamentos candidatos sem feature/valor no Parquet. Invariante auditável do motor.', verbose_name='Readouts Ausentes (fantasma)')),
                ('n_readouts_phospho', models.PositiveIntegerField(default=0, help_text='Nós da Regra 1 que contribuíram (com valor). 0 = caso pareado no proteoma mas não no fosfo → só a Regra 2 pontua.', verbose_name='Readouts de Fosfo (Regra 1)')),
                ('n_readouts_tf', models.PositiveIntegerField(default=0, help_text='TFs com footprint computado (≥ min_regulon_targets alvos com valor). hsa04115 (p53) só tem este termo.', verbose_name='Readouts de TF (Regra 2)')),
                ('method_version', models.CharField(help_text='ex.: fase4-pfs-v1 — PARTE DA NATURAL KEY. Codifica a configuração inteira (seeds, restart, unsigned_weight, B, rng_seed); duas configurações distintas NÃO podem colidir na mesma chave.', max_length=50, verbose_name='Versão do Método')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Computado em')),
                ('pairing', models.ForeignKey(blank=True, help_text='Par que forneceu o baseline normal do readout. NULL é o ponto de extensão reservado a baseline NÃO pareado (GTEx, pendente no roadmap) — no v1 vem sempre preenchido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_scores', to='core.omicsamplepairing')),
                ('pathway', models.ForeignKey(help_text='Via pontuada (o PFS é POR VIA; grafos não são unidos).', on_delete=django.db.models.deletion.CASCADE, related_name='activity_scores', to='core.pathway')),
                ('sample', models.ForeignKey(help_text='Amostra TUMOR do contraste — é ela que carrega as sementes genômicas (D8).', on_delete=django.db.models.deletion.CASCADE, related_name='pathway_scores', to='core.omicsample')),
            ],
            options={
                'verbose_name': 'Pathway activity score',
                'verbose_name_plural': 'Pathway activity scores',
                'indexes': [models.Index(fields=['sample', 'method_version'], name='pathwayscore_sample_mv_idx')],
                'constraints': [models.UniqueConstraint(fields=('pathway', 'sample', 'method_version'), name='pathwayactivityscore_natural_key_uniq')],
            },
        ),
    ]
