# Generated by Django 6.0.3 on 2026-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pathway_activity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='fdr_method',
            field=models.CharField(blank=True, choices=[('benjamini_hochberg', 'Benjamini-Hochberg (FDR)'), ('benjamini_yekutieli', 'Benjamini-Yekutieli (FDR, dep. arbitrária)'), ('storey_q', 'Storey q-value (pi0 estimado)')], db_default='', default='', help_text='"" = nenhuma passada de FDR tocou esta linha. Preenchido = a linha foi CONSIDERADA por uma passada (mesmo que excluída do denominador, caso em que q_value fica NULL).', max_length=24, verbose_name='Método de Correção'),
        ),
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='fdr_n_tests',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='m efetivamente usado como denominador do BH nesta linha, JÁ DESCONTADOS os degenerados. Persistido porque o escopo sozinho não reproduz m: a exclusão depende do estado dos dados no instante da passada. 0 = FDR não computado.', verbose_name='Tamanho da Família (m)'),
        ),
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='fdr_scope',
            field=models.CharField(blank=True, choices=[('global', 'Global: todos os testes deste method_version'), ('pathway_across_samples', 'Por via, através das amostras'), ('sample_across_pathways', 'Por amostra, através das vias')], db_default='', default='', help_text='SEM ISTO O q_value É ININTERPRETÁVEL: BH sobre 31.248 testes globais responde "esta via nesta amostra se destaca em toda a coorte?"; BH sobre as 84 amostras de UMA via responde "quais pacientes têm esta via ativa?"; BH sobre as 372 vias de UM paciente responde "qual a assinatura DESTE paciente?". São três perguntas diferentes e o mesmo p_empirical gera três q diferentes.', max_length=24, verbose_name='Escopo da Correção (família de testes)'),
        ),
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='q_value',
            field=models.FloatField(blank=True, help_text='p_empirical ajustado para multiplicidade dentro da família declarada em fdr_scope. NULL tem DOIS significados, desambiguados por fdr_method: fdr_method=="" → a passada de FDR ainda NÃO rodou nesta linha; fdr_method preenchido e q_value NULL → a linha foi DELIBERADAMENTE excluída do denominador (degenerada: null_sd==0). NUNCA NaN — o CheckConstraint pathwayscore_qvalue_range rejeita NaN (no Postgres NaN > 1.0 é verdadeiro).', null=True, verbose_name='q-valor (FDR)'),
        ),
        migrations.AddConstraint(
            model_name='pathwayactivityscore',
            constraint=models.CheckConstraint(condition=models.Q(('q_value__isnull', True), models.Q(('q_value__gte', 0.0), ('q_value__lte', 1.0)), _connector='OR'), name='pathwayscore_qvalue_range'),
        ),
        migrations.AddConstraint(
            model_name='pathwayactivityscore',
            constraint=models.CheckConstraint(condition=models.Q(('q_value__isnull', True), models.Q(models.Q(('fdr_method', ''), _negated=True), models.Q(('fdr_scope', ''), _negated=True)), _connector='OR'), name='pathwayscore_qvalue_labeled'),
        ),
    ]
