# Generated by Django 6.0.3 on 2026-07-31
#
# FDR do PathwayActivityScore em DOIS ESCOPOS SIMULTÂNEOS (continuação da 0038).
#
# A 0038 entregou UM q por linha, rotulado pelo valor da coluna `fdr_scope`.
# A bancada precisa das duas leituras AO MESMO TEMPO:
#
#   POPULACIONAL  família = as amostras de UMA via   (pathway_id, method_version)
#   INDIVIDUAL    família = as vias de UM paciente   (sample_id,  method_version)
#
# Com DOIS q na mesma linha, um rótulo em COLUNA DE VALOR deixa de funcionar:
# ele descreveria um dos q e o outro ficaria sem rótulo, e nenhuma leitura de
# uma linha crua diria qual q é qual. Esta migration move o escopo do VALOR
# para o NOME DA COLUNA:
#
#   q_value       → q_value_across_samples        (populacional)
#   fdr_method    → fdr_method_across_samples
#   fdr_n_tests   → fdr_n_tests_across_samples
#   fdr_scope     → REMOVIDO (o nome da coluna passa a ser o rótulo)
#   + trio novo   → *_across_pathways             (individual)
#
# RENAME e não DROP/ADD: RENAME preserva dado, tipo, NOT NULL e DEFAULT do
# banco em ALTER TABLE puramente de catálogo. Ainda assim a segurança aqui é
# dupla — as colunas de FDR estão VIRGENS na base do usuário no momento desta
# migration (504 linhas na tabela, 0 com fdr_method<>'', 0 com q_value NOT
# NULL, 0 com fdr_scope<>''): a passada de FDR nunca rodou, então `fdr_scope`
# sai sem plano de migração de dados porque não há dado a migrar. Reverso
# restaura as três colunas originais com o mesmo db_default.
#
# JANELA DO REVERSO (verificado): `migrate core 0038` volta ao shape exato da
# 0038 — colunas, db_default e as 504 linhas intactas. Mas o reverso reintroduz
# `fdr_scope` com db_default '' e o CHECK `pathwayscore_qvalue_labeled`, que
# exige fdr_scope<>'' quando q_value NÃO é NULL. Logo: o reverso é limpo
# ENQUANTO as passadas de FDR não tiverem rodado (q_value_across_samples todo
# NULL). Depois de uma passada populacional, reverter exige antes um UPDATE
# que zere `q_value_across_samples` — que é dado DERIVADO e recomputável, mas
# não some sozinho. Não há reverso "silenciosamente errado": o CHECK barra.
#
# CONTRATO COM O MOTOR RUST — INTOCADO. O `INSERT ... SELECT` de 17 colunas de
# `pfs_engine.rs` (pathway_id, sample_id, pairing_id, score, null_mean,
# null_sd, z_score, p_empirical, n_permutations, n_seeds_on_graph,
# n_seeds_off_graph, n_readouts_mapped, n_readouts_with_value,
# n_readouts_missing, n_readouts_phospho, n_readouts_tf, method_version +
# NOW()) não menciona nenhuma coluna de FDR, nem antes nem depois. Os dois
# NOT NULL novos levam `db_default` (não só `default` Django) pelo mesmo
# motivo da 0020 e da 0038: sem DEFAULT no nível do BANCO, um INSERT com
# SUBSET de colunas quebraria com SqlState 23502 sem que o COPY tivesse mudado
# uma linha sequer.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_pathway_score_fdr'),
    ]

    operations = [
        # 1. Solta os CHECK da 0038 — eles citam colunas que vão ser renomeadas
        #    e uma delas (fdr_scope) vai deixar de existir.
        migrations.RemoveConstraint(
            model_name='pathwayactivityscore',
            name='pathwayscore_qvalue_range',
        ),
        migrations.RemoveConstraint(
            model_name='pathwayactivityscore',
            name='pathwayscore_qvalue_labeled',
        ),

        # 2. O trio da 0038 passa a ser, explicitamente, o escopo POPULACIONAL.
        #    ALTER TABLE ... RENAME COLUMN: preserva dado e DEFAULT do banco.
        migrations.RenameField(
            model_name='pathwayactivityscore',
            old_name='q_value',
            new_name='q_value_across_samples',
        ),
        migrations.RenameField(
            model_name='pathwayactivityscore',
            old_name='fdr_method',
            new_name='fdr_method_across_samples',
        ),
        migrations.RenameField(
            model_name='pathwayactivityscore',
            old_name='fdr_n_tests',
            new_name='fdr_n_tests_across_samples',
        ),

        # 3. Rótulo de escopo em coluna de valor perde a razão de existir:
        #    o sufixo do nome já é o rótulo, e agora ele é POR q.
        migrations.RemoveField(
            model_name='pathwayactivityscore',
            name='fdr_scope',
        ),

        # 4. Trio do escopo INDIVIDUAL — aditivo, espelhando a semântica da
        #    0038 (nullable + rótulo + m efetivo).
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='q_value_across_pathways',
            field=models.FloatField(blank=True, help_text='p_empirical ajustado para multiplicidade DENTRO DA AMOSTRA, através das vias: a família é (sample_id, method_version). NULL tem DOIS significados, desambiguados por fdr_method_across_pathways: método=="" → a passada individual ainda NÃO rodou nesta linha; método preenchido e q NULL → a linha foi DELIBERADAMENTE excluída do denominador (degenerada: null_sd==0). NUNCA NaN — o CheckConstraint pathwayscore_q_across_pathways_range rejeita NaN. NÃO comparável com q_value_across_samples: são famílias diferentes.', null=True, verbose_name='q-valor FDR — individual (amostra através das vias)'),
        ),
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='fdr_method_across_pathways',
            field=models.CharField(blank=True, choices=[('benjamini_hochberg', 'Benjamini-Hochberg (FDR)'), ('benjamini_yekutieli', 'Benjamini-Yekutieli (FDR, dep. arbitrária)'), ('storey_q', 'Storey q-value (pi0 estimado)')], db_default='', default='', help_text='"" = nenhuma passada individual tocou esta linha. Preenchido = a linha foi CONSIDERADA por uma passada (mesmo que excluída do denominador, caso em que q_value_across_pathways fica NULL). Independente do método do escopo populacional: as duas passadas são autônomas.', max_length=24, verbose_name='Método de Correção — individual'),
        ),
        migrations.AddField(
            model_name='pathwayactivityscore',
            name='fdr_n_tests_across_pathways',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='m usado como denominador do BH desta linha no escopo individual — conta VIAS não-degeneradas deste paciente (~100 de 372; ~74% das linhas são degeneradas), JÁ DESCONTADAS as degeneradas. Persistido porque o escopo sozinho não reproduz m. 0 = não computado. DIMENSIONAMENTO DE B: o menor q atingível é m/(B+1) — com m≈100 e B=1000 o piso é 0,101, isto é, NENHUMA via de NENHUM paciente poderia jamais passar a α=0,05, por resolução e não por biologia. É o escopo mais exigente e foi ele que fixou B=10000 (piso 0,010). Reexecutar com B baixo produz "nada significativo" como ARTEFATO.', verbose_name='Tamanho da Família (m) — individual: nº de VIAS'),
        ),

        # 5. Os textos dos campos populacionais passam a nomear o escopo.
        #    Só metadado Django (verbose_name/help_text) — SQL no-op.
        migrations.AlterField(
            model_name='pathwayactivityscore',
            name='q_value_across_samples',
            field=models.FloatField(blank=True, help_text='p_empirical ajustado para multiplicidade DENTRO DA VIA, através das amostras da coorte: a família é (pathway_id, method_version). NULL tem DOIS significados, desambiguados por fdr_method_across_samples: método=="" → a passada populacional ainda NÃO rodou nesta linha; método preenchido e q NULL → a linha foi DELIBERADAMENTE excluída do denominador (degenerada: null_sd==0). NUNCA NaN — o CheckConstraint pathwayscore_q_across_samples_range rejeita NaN (no Postgres NaN > 1.0 é verdadeiro). NÃO comparável com q_value_across_pathways: são famílias diferentes.', null=True, verbose_name='q-valor FDR — populacional (via através das amostras)'),
        ),
        migrations.AlterField(
            model_name='pathwayactivityscore',
            name='fdr_method_across_samples',
            field=models.CharField(blank=True, choices=[('benjamini_hochberg', 'Benjamini-Hochberg (FDR)'), ('benjamini_yekutieli', 'Benjamini-Yekutieli (FDR, dep. arbitrária)'), ('storey_q', 'Storey q-value (pi0 estimado)')], db_default='', default='', help_text='"" = nenhuma passada populacional tocou esta linha. Preenchido = a linha foi CONSIDERADA por uma passada (mesmo que excluída do denominador, caso em que q_value_across_samples fica NULL). Independente do método do escopo individual: as duas passadas são autônomas.', max_length=24, verbose_name='Método de Correção — populacional'),
        ),
        migrations.AlterField(
            model_name='pathwayactivityscore',
            name='fdr_n_tests_across_samples',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='m usado como denominador do BH desta linha no escopo populacional — conta AMOSTRAS não-degeneradas desta via (~84 de 84), JÁ DESCONTADAS as degeneradas. Persistido porque o escopo sozinho não reproduz m: a exclusão depende do estado dos dados no instante da passada. 0 = não computado. DIMENSIONAMENTO DE B: o menor q atingível é m/(B+1), piso aritmético que nenhum sinal fura — com m≈84 e B=1000 o piso é 0,084 e NADA passaria a α=0,05; com B=10000 o piso cai para 0,0084. Por isso o motor deve rodar com n_permutations=10000, não com o default 1000.', verbose_name='Tamanho da Família (m) — populacional: nº de AMOSTRAS'),
        ),

        # 6. Garantias da 0038, agora UMA POR ESCOPO: faixa 0≤q≤1 (que também
        #    rejeita NaN, pois NaN <= 1.0 é FALSO no Postgres) e q não-NULL
        #    exige rótulo de método. O escopo não precisa mais ser exigido:
        #    ele é o nome da coluna.
        migrations.AddConstraint(
            model_name='pathwayactivityscore',
            constraint=models.CheckConstraint(condition=models.Q(('q_value_across_samples__isnull', True), models.Q(('q_value_across_samples__gte', 0.0), ('q_value_across_samples__lte', 1.0)), _connector='OR'), name='pathwayscore_q_across_samples_range'),
        ),
        migrations.AddConstraint(
            model_name='pathwayactivityscore',
            constraint=models.CheckConstraint(condition=models.Q(('q_value_across_samples__isnull', True), models.Q(('fdr_method_across_samples', ''), _negated=True), _connector='OR'), name='pathwayscore_q_across_samples_labeled'),
        ),
        migrations.AddConstraint(
            model_name='pathwayactivityscore',
            constraint=models.CheckConstraint(condition=models.Q(('q_value_across_pathways__isnull', True), models.Q(('q_value_across_pathways__gte', 0.0), ('q_value_across_pathways__lte', 1.0)), _connector='OR'), name='pathwayscore_q_across_pathways_range'),
        ),
        migrations.AddConstraint(
            model_name='pathwayactivityscore',
            constraint=models.CheckConstraint(condition=models.Q(('q_value_across_pathways__isnull', True), models.Q(('fdr_method_across_pathways', ''), _negated=True), _connector='OR'), name='pathwayscore_q_across_pathways_labeled'),
        ),
    ]
