# Generated by Django 6.0.3 on 2026-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_pathway_score_fdr_dual_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='omicmatrix',
            name='omicmatrix_data_format_level_valid',
        ),
        migrations.AlterField(
            model_name='omicmatrix',
            name='data_format_level',
            field=models.CharField(choices=[('counts', 'Counts (contagens brutas)'), ('tpm', 'TPM'), ('fpkm_log2', 'FPKM log2 (RNA-seq, log2 de FPKM)'), ('intensities', 'Intensidades (proteoma/MS)'), ('betas', 'Betas (metilação)'), ('log_ratio', 'Log-ratio (CNV contínuo)')], help_text='Unidade quantitativa da matriz (counts/tpm/fpkm_log2/intensities/betas/log_ratio). fpkm_log2 = log2 de FPKM e NÃO é equivalente a tpm: normalizações distintas (FPKM não soma constante por amostra) e escala logarítmica.', max_length=20, verbose_name='Nível do Formato'),
        ),
        migrations.AddConstraint(
            model_name='omicmatrix',
            constraint=models.CheckConstraint(condition=models.Q(('data_format_level__in', ['counts', 'tpm', 'fpkm_log2', 'intensities', 'betas', 'log_ratio'])), name='omicmatrix_data_format_level_valid'),
        ),
    ]
